import { describe, expect, test } from "bun:test";
import picomatch from "../../src/picomatch/index.ts";

const match = (list: string | string[], pattern: string, options: any = {}): string[] => {
  const isMatch = picomatch(pattern, options, true);
  const matches: Set<string> = options.matches || new Set();
  for (const item of ([] as string[]).concat(list)) {
    const m = (isMatch as any)(item, true);
    if (m && m.output && m.isMatch === true) matches.add(m.output);
  }
  return [...matches];
};

const expect_truthy = (v: unknown) => { expect(Boolean(v)).toBe(true); };
const expect_equal = (actual: unknown, expected: unknown) => {
  expect(actual).toBe(expected as any);
};
const expect_deepEqual = (actual: unknown, expected: unknown) => {
  expect(actual).toEqual(expected as any);
};
const expect_throws = (fn: () => unknown, matcher?: any) => {
  if (matcher) expect(fn).toThrow(matcher);
  else expect(fn).toThrow();
};
const expect_doesNotThrow = (fn: () => unknown) => {
  expect(fn).not.toThrow();
};


const { isMatch } = picomatch;

/**
 * Some of tests were converted from bash 4.3, 4.4, and minimatch unit tests.
 * This is called "temp" as a reminder to reorganize these test and remove duplicates.
 */

describe('extglobs', () => {
  describe('bash', () => {
    test('should match extended globs from the bash spec:', () => {
      expect_truthy(isMatch('bar', '!(foo)', { windows: true }));
      expect_truthy(isMatch('f', '!(foo)', { windows: true }));
      expect_truthy(isMatch('fa', '!(foo)', { windows: true }));
      expect_truthy(isMatch('fb', '!(foo)', { windows: true }));
      expect_truthy(isMatch('ff', '!(foo)', { windows: true }));
      expect_truthy(isMatch('fff', '!(foo)', { windows: true }));
      expect_truthy(isMatch('fo', '!(foo)', { windows: true }));
      expect_truthy(!isMatch('foo', '!(foo)', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(foo)', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(foo)/*', { windows: true }));
      expect_truthy(isMatch('foobar', '!(foo)', { windows: true }));
      expect_truthy(isMatch('foot', '!(foo)', { windows: true }));
      expect_truthy(isMatch('foox', '!(foo)', { windows: true }));
      expect_truthy(isMatch('o', '!(foo)', { windows: true }));
      expect_truthy(isMatch('of', '!(foo)', { windows: true }));
      expect_truthy(isMatch('ooo', '!(foo)', { windows: true }));
      expect_truthy(isMatch('ox', '!(foo)', { windows: true }));
      expect_truthy(isMatch('x', '!(foo)', { windows: true }));
      expect_truthy(isMatch('xx', '!(foo)', { windows: true }));

      expect_truthy(!isMatch('bar', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('f', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('fa', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('fb', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('ff', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('fff', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('fo', '!(!(foo))', { windows: true }));
      expect_truthy(isMatch('foo', '!(!(foo))', { windows: true }));
      expect_truthy(isMatch('foo/bar', '!(!(bar)/baz)', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('foobar', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('foot', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('foox', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('o', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('of', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('ooo', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('ox', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('x', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('xx', '!(!(foo))', { windows: true }));

      expect_truthy(isMatch('bar', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('f', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('fa', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('fb', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('ff', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('fff', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('fo', '!(!(!(foo)))', { windows: true }));
      expect_truthy(!isMatch('foo', '!(!(!(foo)))', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('foobar', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('foot', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('foox', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('o', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('of', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('ooo', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('ox', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('x', '!(!(!(foo)))', { windows: true }));
      expect_truthy(isMatch('xx', '!(!(!(foo)))', { windows: true }));

      expect_truthy(!isMatch('bar', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('f', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('fa', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('fb', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('ff', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('fff', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('fo', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(isMatch('foo', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('foot', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('o', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('of', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('ooo', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('ox', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('x', '!(!(!(!(foo))))', { windows: true }));
      expect_truthy(!isMatch('xx', '!(!(!(!(foo))))', { windows: true }));

      expect_truthy(!isMatch('bar', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('f', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('fa', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('fb', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('ff', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('fff', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('fo', '!(!(foo))*', { windows: true }));
      expect_truthy(isMatch('foo', '!(!(foo))*', { windows: true }));
      expect_truthy(isMatch('foobar', '!(!(foo))*', { windows: true }));
      expect_truthy(isMatch('foot', '!(!(foo))*', { windows: true }));
      expect_truthy(isMatch('foox', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('o', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('of', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('ooo', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('ox', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('x', '!(!(foo))*', { windows: true }));
      expect_truthy(!isMatch('xx', '!(!(foo))*', { windows: true }));

      expect_truthy(isMatch('bar', '!(f!(o))', { windows: true }));
      expect_truthy(!isMatch('f', '!(f!(o))', { windows: true }));
      expect_truthy(!isMatch('fa', '!(f!(o))', { windows: true }));
      expect_truthy(!isMatch('fb', '!(f!(o))', { windows: true }));
      expect_truthy(!isMatch('ff', '!(f!(o))', { windows: true }));
      expect_truthy(!isMatch('fff', '!(f!(o))', { windows: true }));
      expect_truthy(isMatch('fo', '!(f!(o))', { windows: true }));
      expect_truthy(isMatch('foo', '!(!(foo))', { windows: true }));
      expect_truthy(!isMatch('foo', '!(f)!(o)!(o)', { windows: true }));
      expect_truthy(isMatch('foo', '!(fo)', { windows: true }));
      expect_truthy(isMatch('foo', '!(f!(o)*)', { windows: true }));
      expect_truthy(!isMatch('foo', '!(f!(o))', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(f!(o))', { windows: true }));
      expect_truthy(!isMatch('foobar', '!(f!(o))', { windows: true }));
      expect_truthy(isMatch('o', '!(f!(o))', { windows: true }));
      expect_truthy(isMatch('of', '!(f!(o))', { windows: true }));
      expect_truthy(isMatch('ooo', '!(f!(o))', { windows: true }));
      expect_truthy(isMatch('ox', '!(f!(o))', { windows: true }));
      expect_truthy(isMatch('x', '!(f!(o))', { windows: true }));
      expect_truthy(isMatch('xx', '!(f!(o))', { windows: true }));

      expect_truthy(isMatch('bar', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('f', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('fa', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('fb', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('ff', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('fff', '!(f(o))', { windows: true }));
      expect_truthy(!isMatch('fo', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('foo', '!(f(o))', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('foobar', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('foot', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('foox', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('o', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('of', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('ooo', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('ox', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('x', '!(f(o))', { windows: true }));
      expect_truthy(isMatch('xx', '!(f(o))', { windows: true }));

      expect_truthy(isMatch('bar', '!(f)', { windows: true }));
      expect_truthy(!isMatch('f', '!(f)', { windows: true }));
      expect_truthy(isMatch('fa', '!(f)', { windows: true }));
      expect_truthy(isMatch('fb', '!(f)', { windows: true }));
      expect_truthy(isMatch('ff', '!(f)', { windows: true }));
      expect_truthy(isMatch('fff', '!(f)', { windows: true }));
      expect_truthy(isMatch('fo', '!(f)', { windows: true }));
      expect_truthy(isMatch('foo', '!(f)', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(f)', { windows: true }));
      expect_truthy(isMatch('foobar', '!(f)', { windows: true }));
      expect_truthy(isMatch('foot', '!(f)', { windows: true }));
      expect_truthy(isMatch('foox', '!(f)', { windows: true }));
      expect_truthy(isMatch('o', '!(f)', { windows: true }));
      expect_truthy(isMatch('of', '!(f)', { windows: true }));
      expect_truthy(isMatch('ooo', '!(f)', { windows: true }));
      expect_truthy(isMatch('ox', '!(f)', { windows: true }));
      expect_truthy(isMatch('x', '!(f)', { windows: true }));
      expect_truthy(isMatch('xx', '!(f)', { windows: true }));

      expect_truthy(isMatch('bar', '!(f)', { windows: true }));
      expect_truthy(!isMatch('f', '!(f)', { windows: true }));
      expect_truthy(isMatch('fa', '!(f)', { windows: true }));
      expect_truthy(isMatch('fb', '!(f)', { windows: true }));
      expect_truthy(isMatch('ff', '!(f)', { windows: true }));
      expect_truthy(isMatch('fff', '!(f)', { windows: true }));
      expect_truthy(isMatch('fo', '!(f)', { windows: true }));
      expect_truthy(isMatch('foo', '!(f)', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(f)', { windows: true }));
      expect_truthy(isMatch('foobar', '!(f)', { windows: true }));
      expect_truthy(isMatch('foot', '!(f)', { windows: true }));
      expect_truthy(isMatch('foox', '!(f)', { windows: true }));
      expect_truthy(isMatch('o', '!(f)', { windows: true }));
      expect_truthy(isMatch('of', '!(f)', { windows: true }));
      expect_truthy(isMatch('ooo', '!(f)', { windows: true }));
      expect_truthy(isMatch('ox', '!(f)', { windows: true }));
      expect_truthy(isMatch('x', '!(f)', { windows: true }));
      expect_truthy(isMatch('xx', '!(f)', { windows: true }));

      expect_truthy(isMatch('bar', '!(foo)', { windows: true }));
      expect_truthy(isMatch('f', '!(foo)', { windows: true }));
      expect_truthy(isMatch('fa', '!(foo)', { windows: true }));
      expect_truthy(isMatch('fb', '!(foo)', { windows: true }));
      expect_truthy(isMatch('ff', '!(foo)', { windows: true }));
      expect_truthy(isMatch('fff', '!(foo)', { windows: true }));
      expect_truthy(isMatch('fo', '!(foo)', { windows: true }));
      expect_truthy(!isMatch('foo', '!(foo)', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(foo)', { windows: true }));
      expect_truthy(isMatch('foobar', '!(foo)', { windows: true }));
      expect_truthy(isMatch('foot', '!(foo)', { windows: true }));
      expect_truthy(isMatch('foox', '!(foo)', { windows: true }));
      expect_truthy(isMatch('o', '!(foo)', { windows: true }));
      expect_truthy(isMatch('of', '!(foo)', { windows: true }));
      expect_truthy(isMatch('ooo', '!(foo)', { windows: true }));
      expect_truthy(isMatch('ox', '!(foo)', { windows: true }));
      expect_truthy(isMatch('x', '!(foo)', { windows: true }));
      expect_truthy(isMatch('xx', '!(foo)', { windows: true }));

      expect_truthy(isMatch('bar', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('f', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('fa', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('fb', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('ff', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('fff', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('fo', '!(foo)*', { windows: true }));
      expect_truthy(!isMatch('foo', '!(foo)*', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(foo)*', { windows: true }));
      expect_truthy(!isMatch('foobar', '!(foo)*', { windows: true }));
      expect_truthy(!isMatch('foot', '!(foo)*', { windows: true }));
      expect_truthy(!isMatch('foox', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('o', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('of', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('ooo', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('ox', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('x', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('xx', '!(foo)*', { windows: true }));

      expect_truthy(isMatch('bar', '!(x)', { windows: true }));
      expect_truthy(isMatch('f', '!(x)', { windows: true }));
      expect_truthy(isMatch('fa', '!(x)', { windows: true }));
      expect_truthy(isMatch('fb', '!(x)', { windows: true }));
      expect_truthy(isMatch('ff', '!(x)', { windows: true }));
      expect_truthy(isMatch('fff', '!(x)', { windows: true }));
      expect_truthy(isMatch('fo', '!(x)', { windows: true }));
      expect_truthy(isMatch('foo', '!(x)', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(x)', { windows: true }));
      expect_truthy(isMatch('foobar', '!(x)', { windows: true }));
      expect_truthy(isMatch('foot', '!(x)', { windows: true }));
      expect_truthy(isMatch('foox', '!(x)', { windows: true }));
      expect_truthy(isMatch('o', '!(x)', { windows: true }));
      expect_truthy(isMatch('of', '!(x)', { windows: true }));
      expect_truthy(isMatch('ooo', '!(x)', { windows: true }));
      expect_truthy(isMatch('ox', '!(x)', { windows: true }));
      expect_truthy(!isMatch('x', '!(x)', { windows: true }));
      expect_truthy(isMatch('xx', '!(x)', { windows: true }));

      expect_truthy(isMatch('bar', '!(x)*', { windows: true }));
      expect_truthy(isMatch('f', '!(x)*', { windows: true }));
      expect_truthy(isMatch('fa', '!(x)*', { windows: true }));
      expect_truthy(isMatch('fb', '!(x)*', { windows: true }));
      expect_truthy(isMatch('ff', '!(x)*', { windows: true }));
      expect_truthy(isMatch('fff', '!(x)*', { windows: true }));
      expect_truthy(isMatch('fo', '!(x)*', { windows: true }));
      expect_truthy(isMatch('foo', '!(x)*', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '!(x)*', { windows: true }));
      expect_truthy(isMatch('foobar', '!(x)*', { windows: true }));
      expect_truthy(isMatch('foot', '!(x)*', { windows: true }));
      expect_truthy(isMatch('foox', '!(x)*', { windows: true }));
      expect_truthy(isMatch('o', '!(x)*', { windows: true }));
      expect_truthy(isMatch('of', '!(x)*', { windows: true }));
      expect_truthy(isMatch('ooo', '!(x)*', { windows: true }));
      expect_truthy(isMatch('ox', '!(x)*', { windows: true }));
      expect_truthy(!isMatch('x', '!(x)*', { windows: true }));
      expect_truthy(!isMatch('xx', '!(x)*', { windows: true }));

      expect_truthy(isMatch('bar', '*(!(f))', { windows: true }));
      expect_truthy(!isMatch('f', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('fa', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('fb', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('ff', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('fff', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('fo', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('foo', '*(!(f))', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('foobar', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('foot', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('foox', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('o', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('of', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('ooo', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('ox', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('x', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('xx', '*(!(f))', { windows: true }));

      expect_truthy(!isMatch('bar', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('f', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('fa', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('fb', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('ff', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('fff', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('fo', '*((foo))', { windows: true }));
      expect_truthy(isMatch('foo', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('foobar', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('foot', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('foox', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('o', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('of', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('ooo', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('ox', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('x', '*((foo))', { windows: true }));
      expect_truthy(!isMatch('xx', '*((foo))', { windows: true }));

      expect_truthy(isMatch('bar', '+(!(f))', { windows: true }));
      expect_truthy(!isMatch('f', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('fa', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('fb', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('ff', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('fff', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('fo', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('foo', '+(!(f))', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('foobar', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('foot', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('foox', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('o', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('of', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('ooo', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('ox', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('x', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('xx', '+(!(f))', { windows: true }));

      expect_truthy(isMatch('bar', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('f', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fa', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fb', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ff', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fff', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foo/bar', '@(!(z*/*)|*x)', { windows: true }));
      expect_truthy(!isMatch('foo/bar', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foobar', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foot', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('o', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('of', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ooo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('x', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('xx', '@(!(z*)|*x)', { windows: true }));

      expect_truthy(!isMatch('bar', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('f', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('fa', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('fb', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('ff', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('fff', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('fo', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('foo', 'foo/!(foo)', { windows: true }));
      expect_truthy(isMatch('foo/bar', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('foobar', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('foot', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('foox', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('o', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('of', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('ooo', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('ox', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('x', 'foo/!(foo)', { windows: true }));
      expect_truthy(!isMatch('xx', 'foo/!(foo)', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ffo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('fofo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('fofoofoofofoo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foob', '(foo)bb', { windows: true }));
      expect_truthy(isMatch('foobb', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foofoofo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('fooofoofofooo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foooofo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foooofof', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foot', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('foox', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ofoofo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('ooo', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '(foo)bb', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '(foo)bb', { windows: true }));

      expect_truthy(isMatch('ffffffo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('fffooofoooooffoofffooofff', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('ffo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('fofo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('fofoofoofofoo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('foo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('foob', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('foofoofo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('fooofoofofooo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('foooofo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('foooofof', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('foot', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('foox', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('ofoofo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('ofooofoofofooo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('oofooofo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('ooo', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(*(f)*(o))', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(*(f)*(o))', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('ffo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('fofo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('fofoofoofofoo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foob', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foofoofo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('fooofoofofooo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foooofo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foot', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('foox', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('ofoofo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxoo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofxoofxo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ooo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(*(of*(o)x)o)', { windows: true }));

      expect_truthy(isMatch('ffffffo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('fffooofoooooffoofffooofff', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('ffo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('fofo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('fofoofoofofoo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('foo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foob', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('foofoofo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('fooofoofofooo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('foooofo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('foooofof', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foot', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foox', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoofo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ooo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(f*(o))', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ffo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('fofo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('fofoofoofofoo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foob', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foofoofo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('fooofoofofooo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foooofo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(f*(o)x)', { windows: true }));
      expect_truthy(isMatch('foooxfooxfoxfooox', '*(f*(o)x)', { windows: true }));
      expect_truthy(isMatch('foooxfooxfxfooox', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('foot', '*(f*(o)x)', { windows: true }));
      expect_truthy(isMatch('foox', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofoofo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ooo', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(f*(o)x)', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ffo', '*(f+(o))', { windows: true }));
      expect_truthy(isMatch('fofo', '*(f+(o))', { windows: true }));
      expect_truthy(isMatch('fofoofoofofoo', '*(f+(o))', { windows: true }));
      expect_truthy(isMatch('foo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foob', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(f+(o))', { windows: true }));
      expect_truthy(isMatch('foofoofo', '*(f+(o))', { windows: true }));
      expect_truthy(isMatch('fooofoofofooo', '*(f+(o))', { windows: true }));
      expect_truthy(isMatch('foooofo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foot', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foox', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoofo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('ooo', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(f+(o))', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ffo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('fofo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('fofoofoofofoo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foob', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foofoofo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('fooofoofofooo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foot', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('foox', '*(of+(o))', { windows: true }));
      expect_truthy(isMatch('ofoofo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('ooo', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(of+(o))', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(of+(o))', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('ffo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(isMatch('fofo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(isMatch('fofoofoofofoo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foob', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foofoofo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('fooofoofofooo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foooofo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foot', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('foox', '*(of+(o)|f)', { windows: true }));
      expect_truthy(isMatch('ofoofo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(isMatch('ofooofoofofooo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('ooo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(of+(o)|f)', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(of+(o)|f)', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ffo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('fofo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('fofoofoofofoo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foob', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foofoofo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('fooofoofofooo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foot', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('foox', '*(of|oof+(o))', { windows: true }));
      expect_truthy(isMatch('ofoofo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(isMatch('oofooofo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('ooo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(of|oof+(o))', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(of|oof+(o))', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ffo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('fofo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('fofoofoofofoo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foob', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foofoofo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('fooofoofofooo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foooofo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foot', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('foox', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ofoofo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('ooo', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(oxf+(ox))', { windows: true }));
      expect_truthy(isMatch('oxfoxoxfox', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(oxf+(ox))', { windows: true }));

      expect_truthy(isMatch('ffffffo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fffooofoooooffoofffooofff', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ffo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fofo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fofoofoofofoo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foob', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foobb', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foofoofo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fooofoofofooo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foooofo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foooofof', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foooofofx', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foooxfooxfoxfooox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foooxfooxfxfooox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foooxfooxofoxfooox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foot', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ofoofo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ofooofoofofooo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxofo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxoo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxooofxofxo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ofxoofxo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('oofooofo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ooo', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('oxfoxfox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('oxfoxoxfox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('xfoooofof', '@(!(z*)|*x)', { windows: true }));

      expect_truthy(!isMatch('ffffffo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ffo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(isMatch('fofo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(isMatch('fofoofoofofoo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(isMatch('foo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foob', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foobb', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(isMatch('foofoofo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(isMatch('fooofoofofooo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofof', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foot', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('foox', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoofo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('ooo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '@(foo|f|fo)*(f|of+(o))', { windows: true }));

      expect_truthy(isMatch('aaac', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(isMatch('aac', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(isMatch('ac', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(!isMatch('abbcd', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(!isMatch('abcd', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(!isMatch('acd', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(!isMatch('baaac', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(!isMatch('c', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(!isMatch('foo', '*(@(a))a@(c)', { windows: true }));

      expect_truthy(!isMatch('aaac', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('aac', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('ac', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(isMatch('abbcd', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(isMatch('abcd', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(isMatch('acd', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('baaac', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('c', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('foo', '@(ab|a*(b))*(c)d', { windows: true }));

      expect_truthy(!isMatch('aaac', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(!isMatch('aac', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(!isMatch('ac', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(isMatch('abbcd', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(isMatch('abcd', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(!isMatch('acd', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(!isMatch('baaac', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(!isMatch('c', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(!isMatch('foo', '?@(a|b)*@(c)d', { windows: true }));

      expect_truthy(!isMatch('aaac', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('aac', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('ac', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(isMatch('abbcd', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(isMatch('abcd', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('acd', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('baaac', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('c', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(!isMatch('foo', '@(ab|a*@(b))*(c)d', { windows: true }));

      expect_truthy(!isMatch('aac', '*(@(a))b@(c)', { windows: true }));
    });

  });

  describe('other', () => {
    test('should support backtracking in alternation matches', () => {
      expect_truthy(isMatch('fofoofoofofoo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ffffffo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('fffooofoooooffoofffooofff', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ffo', '*(fo|foo)', { windows: true }));
      expect_truthy(isMatch('fofo', '*(fo|foo)', { windows: true }));
      expect_truthy(isMatch('fofoofoofofoo', '*(fo|foo)', { windows: true }));
      expect_truthy(isMatch('foo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foob', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foobb', '*(fo|foo)', { windows: true }));
      expect_truthy(isMatch('foofoofo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('fooofoofofooo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foooofo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfoxfooox', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxfxfooox', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foot', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('foox', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ofoofo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxoo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ofxoofxo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('oofooofo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('ooo', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('oxfoxoxfox', '*(fo|foo)', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(fo|foo)', { windows: true }));
    });

    test('should support exclusions', () => {
      expect_truthy(!isMatch('foob', '!(foo)b*', { windows: true }));
      expect_truthy(!isMatch('foobb', '!(foo)b*', { windows: true }));
      expect_truthy(!isMatch('foo', '!(foo)b*', { windows: true }));
      expect_truthy(isMatch('bar', '!(foo)b*', { windows: true }));
      expect_truthy(isMatch('baz', '!(foo)b*', { windows: true }));
      expect_truthy(!isMatch('foobar', '!(foo)b*', { windows: true }));

      expect_truthy(!isMatch('foo', '*(!(foo))', { windows: true }));
      expect_truthy(isMatch('bar', '*(!(foo))', { windows: true }));
      expect_truthy(isMatch('baz', '*(!(foo))', { windows: true }));
      expect_truthy(isMatch('foobar', '*(!(foo))', { windows: true }));

      // Bash 4.3 says this should match `foo` and `foobar`, which makes no sense
      expect_truthy(!isMatch('foo', '!(foo)*', { windows: true }));
      expect_truthy(!isMatch('foobar', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('bar', '!(foo)*', { windows: true }));
      expect_truthy(isMatch('baz', '!(foo)*', { windows: true }));

      expect_truthy(!isMatch('moo.cow', '!(*.*)', { windows: true }));
      expect_truthy(isMatch('moo', '!(*.*)', { windows: true }));
      expect_truthy(isMatch('cow', '!(*.*)', { windows: true }));

      expect_truthy(isMatch('moo.cow', '!(a*).!(b*)', { windows: true }));
      expect_truthy(!isMatch('moo.cow', '!(*).!(*)', { windows: true }));
      expect_truthy(!isMatch('moo.cow.moo.cow', '!(*.*).!(*.*)', { windows: true }));
      expect_truthy(!isMatch('mad.moo.cow', '!(*.*).!(*.*)', { windows: true }));

      expect_truthy(!isMatch('moo.cow', '!(*.*).', { windows: true }));
      expect_truthy(!isMatch('moo', '!(*.*).', { windows: true }));
      expect_truthy(!isMatch('cow', '!(*.*).', { windows: true }));

      expect_truthy(!isMatch('moo.cow', '.!(*.*)', { windows: true }));
      expect_truthy(!isMatch('moo', '.!(*.*)', { windows: true }));
      expect_truthy(!isMatch('cow', '.!(*.*)', { windows: true }));

      expect_truthy(!isMatch('mucca.pazza', 'mu!(*(c))?.pa!(*(z))?', { windows: true }));

      expect_truthy(isMatch('effgz', '@(b+(c)d|e*(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(isMatch('efgz', '@(b+(c)d|e*(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(isMatch('egz', '@(b+(c)d|e*(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(!isMatch('egz', '@(b+(c)d|e+(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(isMatch('egzefffgzbcdij', '*(b+(c)d|e*(f)g?|?(h)i@(j|k))', { windows: true }));
    });

    test('valid numbers', () => {
      expect_truthy(isMatch('/dev/udp/129.22.8.102/45', '/dev/@(tcp|udp)/*/*', { windows: true }));

      expect_truthy(!isMatch('0', '[1-6]([0-9])', { windows: true }));
      expect_truthy(isMatch('12', '[1-6]([0-9])', { windows: true }));
      expect_truthy(!isMatch('1', '[1-6]([0-9])', { windows: true }));
      expect_truthy(!isMatch('12abc', '[1-6]([0-9])', { windows: true }));
      expect_truthy(!isMatch('555', '[1-6]([0-9])', { windows: true }));

      expect_truthy(!isMatch('0', '[1-6]*([0-9])', { windows: true }));
      expect_truthy(isMatch('12', '[1-6]*([0-9])', { windows: true }));
      expect_truthy(isMatch('1', '[1-6]*([0-9])', { windows: true }));
      expect_truthy(!isMatch('12abc', '[1-6]*([0-9])', { windows: true }));
      expect_truthy(isMatch('555', '[1-6]*([0-9])', { windows: true }));

      expect_truthy(!isMatch('0', '[1-5]*([6-9])', { windows: true }));
      expect_truthy(!isMatch('12', '[1-5]*([6-9])', { windows: true }));
      expect_truthy(isMatch('1', '[1-5]*([6-9])', { windows: true }));
      expect_truthy(!isMatch('12abc', '[1-5]*([6-9])', { windows: true }));
      expect_truthy(!isMatch('555', '[1-5]*([6-9])', { windows: true }));

      expect_truthy(isMatch('0', '0|[1-6]*([0-9])', { windows: true }));
      expect_truthy(isMatch('12', '0|[1-6]*([0-9])', { windows: true }));
      expect_truthy(isMatch('1', '0|[1-6]*([0-9])', { windows: true }));
      expect_truthy(!isMatch('12abc', '0|[1-6]*([0-9])', { windows: true }));
      expect_truthy(isMatch('555', '0|[1-6]*([0-9])', { windows: true }));

      expect_truthy(isMatch('07', '+([0-7])', { windows: true }));
      expect_truthy(isMatch('0377', '+([0-7])', { windows: true }));
      expect_truthy(!isMatch('09', '+([0-7])', { windows: true }));
    });

    test('check extended globbing in pattern removal', () => {
      expect_truthy(isMatch('a', '+(a|abc)', { windows: true }));
      expect_truthy(isMatch('abc', '+(a|abc)', { windows: true }));

      expect_truthy(!isMatch('abcd', '+(a|abc)', { windows: true }));
      expect_truthy(!isMatch('abcde', '+(a|abc)', { windows: true }));
      expect_truthy(!isMatch('abcedf', '+(a|abc)', { windows: true }));

      expect_truthy(isMatch('f', '+(def|f)', { windows: true }));
      expect_truthy(isMatch('def', '+(f|def)', { windows: true }));

      expect_truthy(!isMatch('cdef', '+(f|def)', { windows: true }));
      expect_truthy(!isMatch('bcdef', '+(f|def)', { windows: true }));
      expect_truthy(!isMatch('abcedf', '+(f|def)', { windows: true }));

      expect_truthy(isMatch('abcd', '*(a|b)cd', { windows: true }));

      expect_truthy(!isMatch('a', '*(a|b)cd', { windows: true }));
      expect_truthy(!isMatch('ab', '*(a|b)cd', { windows: true }));
      expect_truthy(!isMatch('abc', '*(a|b)cd', { windows: true }));

      expect_truthy(!isMatch('a', '"*(a|b)cd"', { windows: true }));
      expect_truthy(!isMatch('ab', '"*(a|b)cd"', { windows: true }));
      expect_truthy(!isMatch('abc', '"*(a|b)cd"', { windows: true }));
      expect_truthy(!isMatch('abcde', '"*(a|b)cd"', { windows: true }));
      expect_truthy(!isMatch('abcdef', '"*(a|b)cd"', { windows: true }));
    });

    test('More tests derived from a bug report (in bash) concerning extended glob patterns following a *', () => {
      expect_truthy(isMatch('/dev/udp/129.22.8.102/45', '/dev\\/@(tcp|udp)\\/*\\/*', { windows: true }));
      expect_truthy(!isMatch('123abc', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('ab', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('abab', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('abcdef', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('accdef', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('abcfefg', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('abef', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('abcfef', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('abd', '(a+|b)*', { windows: true }));
      expect_truthy(isMatch('acd', '(a+|b)*', { windows: true }));

      expect_truthy(!isMatch('123abc', '(a+|b)+', { windows: true }));
      expect_truthy(isMatch('ab', '(a+|b)+', { windows: true }));
      expect_truthy(isMatch('abab', '(a+|b)+', { windows: true }));
      expect_truthy(!isMatch('abcdef', '(a+|b)+', { windows: true }));
      expect_truthy(!isMatch('accdef', '(a+|b)+', { windows: true }));
      expect_truthy(!isMatch('abcfefg', '(a+|b)+', { windows: true }));
      expect_truthy(!isMatch('abef', '(a+|b)+', { windows: true }));
      expect_truthy(!isMatch('abcfef', '(a+|b)+', { windows: true }));
      expect_truthy(!isMatch('abd', '(a+|b)+', { windows: true }));
      expect_truthy(!isMatch('acd', '(a+|b)+', { windows: true }));

      expect_truthy(!isMatch('123abc', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(!isMatch('ab', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(!isMatch('abab', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(!isMatch('abcdef', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(!isMatch('accdef', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(!isMatch('abcfefg', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(!isMatch('abef', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(!isMatch('abcfef', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(isMatch('abd', 'a(b*(foo|bar))d', { windows: true }));
      expect_truthy(!isMatch('acd', 'a(b*(foo|bar))d', { windows: true }));

      expect_truthy(!isMatch('123abc', 'ab*(e|f)', { windows: true }));
      expect_truthy(isMatch('ab', 'ab*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abab', 'ab*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcdef', 'ab*(e|f)', { windows: true }));
      expect_truthy(!isMatch('accdef', 'ab*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcfefg', 'ab*(e|f)', { windows: true }));
      expect_truthy(isMatch('abef', 'ab*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcfef', 'ab*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abd', 'ab*(e|f)', { windows: true }));
      expect_truthy(!isMatch('acd', 'ab*(e|f)', { windows: true }));

      expect_truthy(!isMatch('123abc', 'ab**(e|f)', { windows: true }));
      expect_truthy(isMatch('ab', 'ab**(e|f)', { windows: true }));
      expect_truthy(isMatch('abab', 'ab**(e|f)', { windows: true }));
      expect_truthy(isMatch('abcdef', 'ab**(e|f)', { windows: true }));
      expect_truthy(!isMatch('accdef', 'ab**(e|f)', { windows: true }));
      expect_truthy(isMatch('abcfefg', 'ab**(e|f)', { windows: true }));
      expect_truthy(isMatch('abef', 'ab**(e|f)', { windows: true }));
      expect_truthy(isMatch('abcfef', 'ab**(e|f)', { windows: true }));
      expect_truthy(isMatch('abd', 'ab**(e|f)', { windows: true }));
      expect_truthy(!isMatch('acd', 'ab**(e|f)', { windows: true }));

      expect_truthy(!isMatch('123abc', 'ab**(e|f)g', { windows: true }));
      expect_truthy(!isMatch('ab', 'ab**(e|f)g', { windows: true }));
      expect_truthy(!isMatch('abab', 'ab**(e|f)g', { windows: true }));
      expect_truthy(!isMatch('abcdef', 'ab**(e|f)g', { windows: true }));
      expect_truthy(!isMatch('accdef', 'ab**(e|f)g', { windows: true }));
      expect_truthy(isMatch('abcfefg', 'ab**(e|f)g', { windows: true }));
      expect_truthy(!isMatch('abef', 'ab**(e|f)g', { windows: true }));
      expect_truthy(!isMatch('abcfef', 'ab**(e|f)g', { windows: true }));
      expect_truthy(!isMatch('abd', 'ab**(e|f)g', { windows: true }));
      expect_truthy(!isMatch('acd', 'ab**(e|f)g', { windows: true }));

      expect_truthy(!isMatch('123abc', 'ab***ef', { windows: true }));
      expect_truthy(!isMatch('ab', 'ab***ef', { windows: true }));
      expect_truthy(!isMatch('abab', 'ab***ef', { windows: true }));
      expect_truthy(isMatch('abcdef', 'ab***ef', { windows: true }));
      expect_truthy(!isMatch('accdef', 'ab***ef', { windows: true }));
      expect_truthy(!isMatch('abcfefg', 'ab***ef', { windows: true }));
      expect_truthy(isMatch('abef', 'ab***ef', { windows: true }));
      expect_truthy(isMatch('abcfef', 'ab***ef', { windows: true }));
      expect_truthy(!isMatch('abd', 'ab***ef', { windows: true }));
      expect_truthy(!isMatch('acd', 'ab***ef', { windows: true }));

      expect_truthy(!isMatch('123abc', 'ab*+(e|f)', { windows: true }));
      expect_truthy(!isMatch('ab', 'ab*+(e|f)', { windows: true }));
      expect_truthy(!isMatch('abab', 'ab*+(e|f)', { windows: true }));
      expect_truthy(isMatch('abcdef', 'ab*+(e|f)', { windows: true }));
      expect_truthy(!isMatch('accdef', 'ab*+(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcfefg', 'ab*+(e|f)', { windows: true }));
      expect_truthy(isMatch('abef', 'ab*+(e|f)', { windows: true }));
      expect_truthy(isMatch('abcfef', 'ab*+(e|f)', { windows: true }));
      expect_truthy(!isMatch('abd', 'ab*+(e|f)', { windows: true }));
      expect_truthy(!isMatch('acd', 'ab*+(e|f)', { windows: true }));

      expect_truthy(!isMatch('123abc', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(!isMatch('ab', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abab', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(isMatch('abcdef', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(!isMatch('accdef', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcfefg', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abef', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcfef', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(isMatch('abd', 'ab*d*(e|f)', { windows: true }));
      expect_truthy(!isMatch('acd', 'ab*d*(e|f)', { windows: true }));

      expect_truthy(!isMatch('123abc', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(!isMatch('ab', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(!isMatch('abab', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(isMatch('abcdef', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(!isMatch('accdef', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcfefg', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(!isMatch('abef', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcfef', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(!isMatch('abd', 'ab*d+(e|f)', { windows: true }));
      expect_truthy(!isMatch('acd', 'ab*d+(e|f)', { windows: true }));

      expect_truthy(!isMatch('123abc', 'ab?*(e|f)', { windows: true }));
      expect_truthy(!isMatch('ab', 'ab?*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abab', 'ab?*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcdef', 'ab?*(e|f)', { windows: true }));
      expect_truthy(!isMatch('accdef', 'ab?*(e|f)', { windows: true }));
      expect_truthy(!isMatch('abcfefg', 'ab?*(e|f)', { windows: true }));
      expect_truthy(isMatch('abef', 'ab?*(e|f)', { windows: true }));
      expect_truthy(isMatch('abcfef', 'ab?*(e|f)', { windows: true }));
      expect_truthy(isMatch('abd', 'ab?*(e|f)', { windows: true }));
      expect_truthy(!isMatch('acd', 'ab?*(e|f)', { windows: true }));
    });

    test('bug in all versions up to and including bash-2.05b', () => {
      expect_truthy(isMatch('123abc', '*?(a)bc', { windows: true }));
    });

    test('should work with character classes', () => {
      const opts = { posix: true };
      expect_truthy(isMatch('a.b', 'a[^[:alnum:]]b', opts));
      expect_truthy(isMatch('a,b', 'a[^[:alnum:]]b', opts));
      expect_truthy(isMatch('a:b', 'a[^[:alnum:]]b', opts));
      expect_truthy(isMatch('a-b', 'a[^[:alnum:]]b', opts));
      expect_truthy(isMatch('a;b', 'a[^[:alnum:]]b', opts));
      expect_truthy(isMatch('a b', 'a[^[:alnum:]]b', opts));
      expect_truthy(isMatch('a_b', 'a[^[:alnum:]]b', opts));

      expect_truthy(isMatch('a.b', 'a[-.,:\\;\\ _]b', { windows: true }));
      expect_truthy(isMatch('a,b', 'a[-.,:\\;\\ _]b', { windows: true }));
      expect_truthy(isMatch('a:b', 'a[-.,:\\;\\ _]b', { windows: true }));
      expect_truthy(isMatch('a-b', 'a[-.,:\\;\\ _]b', { windows: true }));
      expect_truthy(isMatch('a;b', 'a[-.,:\\;\\ _]b', { windows: true }));
      expect_truthy(isMatch('a b', 'a[-.,:\\;\\ _]b', { windows: true }));
      expect_truthy(isMatch('a_b', 'a[-.,:\\;\\ _]b', { windows: true }));

      expect_truthy(isMatch('a.b', 'a@([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a,b', 'a@([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a:b', 'a@([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a-b', 'a@([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a;b', 'a@([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a b', 'a@([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a_b', 'a@([^[:alnum:]])b', opts));

      expect_truthy(isMatch('a.b', 'a@([-.,:; _])b', { windows: true }));
      expect_truthy(isMatch('a,b', 'a@([-.,:; _])b', { windows: true }));
      expect_truthy(isMatch('a:b', 'a@([-.,:; _])b', { windows: true }));
      expect_truthy(isMatch('a-b', 'a@([-.,:; _])b', { windows: true }));
      expect_truthy(isMatch('a;b', 'a@([-.,:; _])b', { windows: true }));
      expect_truthy(isMatch('a b', 'a@([-.,:; _])b', { windows: true }));
      expect_truthy(isMatch('a_b', 'a@([-.,:; _])b', { windows: true }));

      expect_truthy(isMatch('a.b', 'a@([.])b', { windows: true }));
      expect_truthy(!isMatch('a,b', 'a@([.])b', { windows: true }));
      expect_truthy(!isMatch('a:b', 'a@([.])b', { windows: true }));
      expect_truthy(!isMatch('a-b', 'a@([.])b', { windows: true }));
      expect_truthy(!isMatch('a;b', 'a@([.])b', { windows: true }));
      expect_truthy(!isMatch('a b', 'a@([.])b', { windows: true }));
      expect_truthy(!isMatch('a_b', 'a@([.])b', { windows: true }));

      expect_truthy(!isMatch('a.b', 'a@([^.])b', { windows: true }));
      expect_truthy(isMatch('a,b', 'a@([^.])b', { windows: true }));
      expect_truthy(isMatch('a:b', 'a@([^.])b', { windows: true }));
      expect_truthy(isMatch('a-b', 'a@([^.])b', { windows: true }));
      expect_truthy(isMatch('a;b', 'a@([^.])b', { windows: true }));
      expect_truthy(isMatch('a b', 'a@([^.])b', { windows: true }));
      expect_truthy(isMatch('a_b', 'a@([^.])b', { windows: true }));

      expect_truthy(isMatch('a.b', 'a@([^x])b', { windows: true }));
      expect_truthy(isMatch('a,b', 'a@([^x])b', { windows: true }));
      expect_truthy(isMatch('a:b', 'a@([^x])b', { windows: true }));
      expect_truthy(isMatch('a-b', 'a@([^x])b', { windows: true }));
      expect_truthy(isMatch('a;b', 'a@([^x])b', { windows: true }));
      expect_truthy(isMatch('a b', 'a@([^x])b', { windows: true }));
      expect_truthy(isMatch('a_b', 'a@([^x])b', { windows: true }));

      expect_truthy(isMatch('a.b', 'a+([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a,b', 'a+([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a:b', 'a+([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a-b', 'a+([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a;b', 'a+([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a b', 'a+([^[:alnum:]])b', opts));
      expect_truthy(isMatch('a_b', 'a+([^[:alnum:]])b', opts));

      expect_truthy(isMatch('a.b', 'a@(.|[^[:alnum:]])b', opts));
      expect_truthy(isMatch('a,b', 'a@(.|[^[:alnum:]])b', opts));
      expect_truthy(isMatch('a:b', 'a@(.|[^[:alnum:]])b', opts));
      expect_truthy(isMatch('a-b', 'a@(.|[^[:alnum:]])b', opts));
      expect_truthy(isMatch('a;b', 'a@(.|[^[:alnum:]])b', opts));
      expect_truthy(isMatch('a b', 'a@(.|[^[:alnum:]])b', opts));
      expect_truthy(isMatch('a_b', 'a@(.|[^[:alnum:]])b', opts));
    });

    test('should support POSIX character classes in extglobs', () => {
      const opts = { posix: true };
      expect_truthy(isMatch('a.c', '+([[:alpha:].])', opts));
      expect_truthy(isMatch('a.c', '+([[:alpha:].])+([[:alpha:].])', opts));
      expect_truthy(isMatch('a.c', '*([[:alpha:].])', opts));
      expect_truthy(isMatch('a.c', '*([[:alpha:].])*([[:alpha:].])', opts));
      expect_truthy(isMatch('a.c', '?([[:alpha:].])?([[:alpha:].])?([[:alpha:].])', opts));
      expect_truthy(isMatch('a.c', '@([[:alpha:].])@([[:alpha:].])@([[:alpha:].])', opts));
      expect_truthy(!isMatch('.', '!(\\.)', opts));
      expect_truthy(!isMatch('.', '!([[:alpha:].])', opts));
      expect_truthy(isMatch('.', '?([[:alpha:].])', opts));
      expect_truthy(isMatch('.', '@([[:alpha:].])', opts));
    });

    // ported from http://www.bashcookbook.com/bashinfo/source/bash-4.3/tests/extglob2.tests
    test('should pass extglob2 tests', () => {
      expect_truthy(!isMatch('baaac', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(!isMatch('c', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(!isMatch('egz', '@(b+(c)d|e+(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(!isMatch('foooofof', '*(f+(o))', { windows: true }));
      expect_truthy(!isMatch('foooofofx', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('foooxfooxofoxfooox', '*(f*(o)x)', { windows: true }));
      expect_truthy(!isMatch('ofooofoofofooo', '*(f*(o))', { windows: true }));
      expect_truthy(!isMatch('ofoooxoofxoofoooxoofxofo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(!isMatch('oxfoxfox', '*(oxf+(ox))', { windows: true }));
      expect_truthy(!isMatch('xfoooofof', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('aaac', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(isMatch('aac', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(isMatch('abbcd', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(isMatch('abcd', '?@(a|b)*@(c)d', { windows: true }));
      expect_truthy(isMatch('abcd', '@(ab|a*@(b))*(c)d', { windows: true }));
      expect_truthy(isMatch('ac', '*(@(a))a@(c)', { windows: true }));
      expect_truthy(isMatch('acd', '@(ab|a*(b))*(c)d', { windows: true }));
      expect_truthy(isMatch('effgz', '@(b+(c)d|e*(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(isMatch('efgz', '@(b+(c)d|e*(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(isMatch('egz', '@(b+(c)d|e*(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(isMatch('egzefffgzbcdij', '*(b+(c)d|e*(f)g?|?(h)i@(j|k))', { windows: true }));
      expect_truthy(isMatch('fffooofoooooffoofffooofff', '*(*(f)*(o))', { windows: true }));
      expect_truthy(isMatch('ffo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('fofo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('foofoofo', '@(foo|f|fo)*(f|of+(o))', { windows: true }));
      expect_truthy(isMatch('fooofoofofooo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('foooofo', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('foooofof', '*(f*(o))', { windows: true }));
      expect_truthy(isMatch('foooxfooxfoxfooox', '*(f*(o)x)', { windows: true }));
      expect_truthy(isMatch('foooxfooxfxfooox', '*(f*(o)x)', { windows: true }));
      expect_truthy(isMatch('ofoofo', '*(of+(o))', { windows: true }));
      expect_truthy(isMatch('ofoofo', '*(of+(o)|f)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxoo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofoooxoofxoofoooxoofxooofxofxo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('ofxoofxo', '*(*(of*(o)x)o)', { windows: true }));
      expect_truthy(isMatch('oofooofo', '*(of|oof+(o))', { windows: true }));
      expect_truthy(isMatch('oxfoxoxfox', '*(oxf+(ox))', { windows: true }));
    });

    test('should support exclusions', () => {
      expect_truthy(!isMatch('f', '!(f)', { windows: true }));
      expect_truthy(!isMatch('f', '*(!(f))', { windows: true }));
      expect_truthy(!isMatch('f', '+(!(f))', { windows: true }));
      expect_truthy(!isMatch('foo', '!(foo)', { windows: true }));
      expect_truthy(!isMatch('foob', '!(foo)b*', { windows: true }));
      expect_truthy(!isMatch('mad.moo.cow', '!(*.*).!(*.*)', { windows: true }));
      expect_truthy(!isMatch('mucca.pazza', 'mu!(*(c))?.pa!(*(z))?', { windows: true }));
      expect_truthy(!isMatch('zoot', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('fff', '!(f)', { windows: true }));
      expect_truthy(isMatch('fff', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('fff', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('foo', '!(f)', { windows: true }));
      expect_truthy(isMatch('foo', '!(x)', { windows: true }));
      expect_truthy(isMatch('foo', '!(x)*', { windows: true }));
      expect_truthy(isMatch('foo', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('foo', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('foobar', '!(foo)', { windows: true }));
      expect_truthy(isMatch('foot', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('foox', '@(!(z*)|*x)', { windows: true }));
      expect_truthy(isMatch('ooo', '!(f)', { windows: true }));
      expect_truthy(isMatch('ooo', '*(!(f))', { windows: true }));
      expect_truthy(isMatch('ooo', '+(!(f))', { windows: true }));
      expect_truthy(isMatch('zoox', '@(!(z*)|*x)', { windows: true }));
    });
  });
});

