import { describe, expect, test } from "bun:test";
import picomatch from "../../src/picomatch/index.ts";

const match = (list: string | string[], pattern: string, options: any = {}): string[] => {
  const isMatch = picomatch(pattern, options, true);
  const matches: Set<string> = options.matches || new Set();
  for (const item of ([] as string[]).concat(list)) {
    const m = (isMatch as any)(item, true);
    if (m && m.output && m.isMatch === true) matches.add(m.output);
  }
  return [...matches];
};

const expect_truthy = (v: unknown) => { expect(Boolean(v)).toBe(true); };
const expect_equal = (actual: unknown, expected: unknown) => {
  expect(actual).toBe(expected as any);
};
const expect_deepEqual = (actual: unknown, expected: unknown) => {
  expect(actual).toEqual(expected as any);
};
const expect_throws = (fn: () => unknown, matcher?: any) => {
  if (matcher) expect(fn).toThrow(matcher);
  else expect(fn).toThrow();
};
const expect_doesNotThrow = (fn: () => unknown) => {
  expect(fn).not.toThrow();
};


const { isMatch } = picomatch;

describe('slash handling - posix', () => {
  test('should match a literal string', () => {
    expect_truthy(!isMatch('a/a', '(a/b)'));
    expect_truthy(isMatch('a/b', '(a/b)'));
    expect_truthy(!isMatch('a/c', '(a/b)'));
    expect_truthy(!isMatch('b/a', '(a/b)'));
    expect_truthy(!isMatch('b/b', '(a/b)'));
    expect_truthy(!isMatch('b/c', '(a/b)'));

    expect_truthy(!isMatch('a/a', 'a/b'));
    expect_truthy(isMatch('a/b', 'a/b'));
    expect_truthy(!isMatch('a/c', 'a/b'));
    expect_truthy(!isMatch('b/a', 'a/b'));
    expect_truthy(!isMatch('b/b', 'a/b'));
    expect_truthy(!isMatch('b/c', 'a/b'));
  });

  test('should match an array of literal strings', () => {
    expect_truthy(!isMatch('a/a', 'a/b'));
    expect_truthy(isMatch('a/b', 'a/b'));
    expect_truthy(!isMatch('a/c', 'a/b'));
    expect_truthy(!isMatch('b/a', 'a/b'));
    expect_truthy(!isMatch('b/b', 'a/b'));
    expect_truthy(isMatch('b/b', 'b/b'));
    expect_truthy(!isMatch('b/c', 'a/b'));
  });

  test('should support regex logical or', () => {
    expect_truthy(isMatch('a/a', 'a/(a|c)'));
    expect_truthy(!isMatch('a/b', 'a/(a|c)'));
    expect_truthy(isMatch('a/c', 'a/(a|c)'));

    expect_truthy(isMatch('a/a', 'a/(a|b|c)'));
    expect_truthy(isMatch('a/b', 'a/(a|b|c)'));
    expect_truthy(isMatch('a/c', 'a/(a|b|c)'));
  });

  test('should support regex ranges', () => {
    expect_truthy(!isMatch('a/a', 'a/[b-c]'));
    expect_truthy(isMatch('a/b', 'a/[b-c]'));
    expect_truthy(isMatch('a/c', 'a/[b-c]'));

    expect_truthy(isMatch('a/a', 'a/[a-z]'));
    expect_truthy(isMatch('a/b', 'a/[a-z]'));
    expect_truthy(isMatch('a/c', 'a/[a-z]'));
    expect_truthy(!isMatch('a/x/y', 'a/[a-z]'));
    expect_truthy(isMatch('a/x', 'a/[a-z]'));
  });

  test('should support single globs (*)', () => {
    expect_truthy(isMatch('a', '*'));
    expect_truthy(isMatch('b', '*'));
    expect_truthy(!isMatch('a/a', '*'));
    expect_truthy(!isMatch('a/b', '*'));
    expect_truthy(!isMatch('a/c', '*'));
    expect_truthy(!isMatch('a/x', '*'));
    expect_truthy(!isMatch('a/a/a', '*'));
    expect_truthy(!isMatch('a/a/b', '*'));
    expect_truthy(!isMatch('a/a/a/a', '*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*'));
    expect_truthy(!isMatch('x/y', '*'));
    expect_truthy(!isMatch('z/z', '*'));

    expect_truthy(!isMatch('a', '*/*'));
    expect_truthy(!isMatch('b', '*/*'));
    expect_truthy(isMatch('a/a', '*/*'));
    expect_truthy(isMatch('a/b', '*/*'));
    expect_truthy(isMatch('a/c', '*/*'));
    expect_truthy(isMatch('a/x', '*/*'));
    expect_truthy(!isMatch('a/a/a', '*/*'));
    expect_truthy(!isMatch('a/a/b', '*/*'));
    expect_truthy(!isMatch('a/a/a/a', '*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*'));
    expect_truthy(isMatch('x/y', '*/*'));
    expect_truthy(isMatch('z/z', '*/*'));

    expect_truthy(!isMatch('a', '*/*/*'));
    expect_truthy(!isMatch('b', '*/*/*'));
    expect_truthy(!isMatch('a/a', '*/*/*'));
    expect_truthy(!isMatch('a/b', '*/*/*'));
    expect_truthy(!isMatch('a/c', '*/*/*'));
    expect_truthy(!isMatch('a/x', '*/*/*'));
    expect_truthy(isMatch('a/a/a', '*/*/*'));
    expect_truthy(isMatch('a/a/b', '*/*/*'));
    expect_truthy(!isMatch('a/a/a/a', '*/*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*/*'));
    expect_truthy(!isMatch('x/y', '*/*/*'));
    expect_truthy(!isMatch('z/z', '*/*/*'));

    expect_truthy(!isMatch('a', '*/*/*/*'));
    expect_truthy(!isMatch('b', '*/*/*/*'));
    expect_truthy(!isMatch('a/a', '*/*/*/*'));
    expect_truthy(!isMatch('a/b', '*/*/*/*'));
    expect_truthy(!isMatch('a/c', '*/*/*/*'));
    expect_truthy(!isMatch('a/x', '*/*/*/*'));
    expect_truthy(!isMatch('a/a/a', '*/*/*/*'));
    expect_truthy(!isMatch('a/a/b', '*/*/*/*'));
    expect_truthy(isMatch('a/a/a/a', '*/*/*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*/*/*'));
    expect_truthy(!isMatch('x/y', '*/*/*/*'));
    expect_truthy(!isMatch('z/z', '*/*/*/*'));

    expect_truthy(!isMatch('a', '*/*/*/*/*'));
    expect_truthy(!isMatch('b', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/a', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/b', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/c', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/x', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/a/a', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/a/b', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/a/a/a', '*/*/*/*/*'));
    expect_truthy(isMatch('a/a/a/a/a', '*/*/*/*/*'));
    expect_truthy(!isMatch('x/y', '*/*/*/*/*'));
    expect_truthy(!isMatch('z/z', '*/*/*/*/*'));

    expect_truthy(!isMatch('a', 'a/*'));
    expect_truthy(!isMatch('b', 'a/*'));
    expect_truthy(isMatch('a/a', 'a/*'));
    expect_truthy(isMatch('a/b', 'a/*'));
    expect_truthy(isMatch('a/c', 'a/*'));
    expect_truthy(isMatch('a/x', 'a/*'));
    expect_truthy(!isMatch('a/a/a', 'a/*'));
    expect_truthy(!isMatch('a/a/b', 'a/*'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*'));
    expect_truthy(!isMatch('x/y', 'a/*'));
    expect_truthy(!isMatch('z/z', 'a/*'));

    expect_truthy(!isMatch('a', 'a/*/*'));
    expect_truthy(!isMatch('b', 'a/*/*'));
    expect_truthy(!isMatch('a/a', 'a/*/*'));
    expect_truthy(!isMatch('a/b', 'a/*/*'));
    expect_truthy(!isMatch('a/c', 'a/*/*'));
    expect_truthy(!isMatch('a/x', 'a/*/*'));
    expect_truthy(isMatch('a/a/a', 'a/*/*'));
    expect_truthy(isMatch('a/a/b', 'a/*/*'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/*'));
    expect_truthy(!isMatch('x/y', 'a/*/*'));
    expect_truthy(!isMatch('z/z', 'a/*/*'));

    expect_truthy(!isMatch('a', 'a/*/*/*'));
    expect_truthy(!isMatch('b', 'a/*/*/*'));
    expect_truthy(!isMatch('a/a', 'a/*/*/*'));
    expect_truthy(!isMatch('a/b', 'a/*/*/*'));
    expect_truthy(!isMatch('a/c', 'a/*/*/*'));
    expect_truthy(!isMatch('a/x', 'a/*/*/*'));
    expect_truthy(!isMatch('a/a/a', 'a/*/*/*'));
    expect_truthy(!isMatch('a/a/b', 'a/*/*/*'));
    expect_truthy(isMatch('a/a/a/a', 'a/*/*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/*/*'));
    expect_truthy(!isMatch('x/y', 'a/*/*/*'));
    expect_truthy(!isMatch('z/z', 'a/*/*/*'));

    expect_truthy(!isMatch('a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('b', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/b', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/c', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/x', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/a/a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/a/b', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/*/*/*'));
    expect_truthy(isMatch('a/a/a/a/a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('x/y', 'a/*/*/*/*'));
    expect_truthy(!isMatch('z/z', 'a/*/*/*/*'));

    expect_truthy(!isMatch('a', 'a/*/a'));
    expect_truthy(!isMatch('b', 'a/*/a'));
    expect_truthy(!isMatch('a/a', 'a/*/a'));
    expect_truthy(!isMatch('a/b', 'a/*/a'));
    expect_truthy(!isMatch('a/c', 'a/*/a'));
    expect_truthy(!isMatch('a/x', 'a/*/a'));
    expect_truthy(isMatch('a/a/a', 'a/*/a'));
    expect_truthy(!isMatch('a/a/b', 'a/*/a'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/a'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/a'));
    expect_truthy(!isMatch('x/y', 'a/*/a'));
    expect_truthy(!isMatch('z/z', 'a/*/a'));

    expect_truthy(!isMatch('a', 'a/*/b'));
    expect_truthy(!isMatch('b', 'a/*/b'));
    expect_truthy(!isMatch('a/a', 'a/*/b'));
    expect_truthy(!isMatch('a/b', 'a/*/b'));
    expect_truthy(!isMatch('a/c', 'a/*/b'));
    expect_truthy(!isMatch('a/x', 'a/*/b'));
    expect_truthy(!isMatch('a/a/a', 'a/*/b'));
    expect_truthy(isMatch('a/a/b', 'a/*/b'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/b'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/b'));
    expect_truthy(!isMatch('x/y', 'a/*/b'));
    expect_truthy(!isMatch('z/z', 'a/*/b'));
  });

  test('should support globstars (**)', () => {
    expect_truthy(isMatch('a', 'a'));
    expect_truthy(!isMatch('a/', 'a'));
    expect_truthy(!isMatch('a/a', 'a'));
    expect_truthy(!isMatch('a/b', 'a'));
    expect_truthy(!isMatch('a/c', 'a'));
    expect_truthy(!isMatch('a/x', 'a'));
    expect_truthy(!isMatch('a/x/y', 'a'));
    expect_truthy(!isMatch('a/x/y/z', 'a'));

    expect_truthy(isMatch('a', '*'));
    expect_truthy(isMatch('a/', '*', { relaxSlashes: true }));
    expect_truthy(isMatch('a/', '*{,/}'));
    expect_truthy(!isMatch('a/a', '*'));
    expect_truthy(!isMatch('a/b', '*'));
    expect_truthy(!isMatch('a/c', '*'));
    expect_truthy(!isMatch('a/x', '*'));
    expect_truthy(!isMatch('a/x/y', '*'));
    expect_truthy(!isMatch('a/x/y/z', '*'));

    expect_truthy(!isMatch('a', '*/'));
    expect_truthy(isMatch('a/', '*/'));
    expect_truthy(!isMatch('a/a', '*/'));
    expect_truthy(!isMatch('a/b', '*/'));
    expect_truthy(!isMatch('a/c', '*/'));
    expect_truthy(!isMatch('a/x', '*/'));
    expect_truthy(!isMatch('a/x/y', '*/'));
    expect_truthy(!isMatch('a/x/y/z', '*/'));

    expect_truthy(!isMatch('a', '*/*'));
    expect_truthy(!isMatch('a/', '*/*'));
    expect_truthy(isMatch('a/a', '*/*'));
    expect_truthy(isMatch('a/b', '*/*'));
    expect_truthy(isMatch('a/c', '*/*'));
    expect_truthy(isMatch('a/x', '*/*'));
    expect_truthy(!isMatch('a/x/y', '*/*'));
    expect_truthy(!isMatch('a/x/y/z', '*/*'));

    expect_truthy(isMatch('a', '**'));
    expect_truthy(isMatch('a/', '**'));
    expect_truthy(isMatch('a/a', '**'));
    expect_truthy(isMatch('a/b', '**'));
    expect_truthy(isMatch('a/c', '**'));
    expect_truthy(isMatch('a/x', '**'));
    expect_truthy(isMatch('a/x/y', '**'));
    expect_truthy(isMatch('a/x/y/z', '**'));

    expect_truthy(!isMatch('a/', '**/a'));
    expect_truthy(!isMatch('a/b', '**/a'));
    expect_truthy(!isMatch('a/c', '**/a'));
    expect_truthy(!isMatch('a/x', '**/a'));
    expect_truthy(!isMatch('a/x/y/z', '**/a'));
    expect_truthy(isMatch('a/x/y/z/a', '**/a'));
    expect_truthy(isMatch('a', '**/a'));
    expect_truthy(isMatch('a/a', '**/a'));

    expect_truthy(!isMatch('a', 'a/*'));
    expect_truthy(!isMatch('a/', 'a/*'));
    expect_truthy(isMatch('a/a', 'a/*'));
    expect_truthy(isMatch('a/b', 'a/*'));
    expect_truthy(isMatch('a/c', 'a/*'));
    expect_truthy(isMatch('a/x', 'a/*'));
    expect_truthy(!isMatch('a/x/y', 'a/*'));
    expect_truthy(!isMatch('a/x/y/z', 'a/*'));

    expect_truthy(isMatch('a', 'a/**'));
    expect_truthy(isMatch('a/', 'a/**'));
    expect_truthy(isMatch('a/a', 'a/**'));
    expect_truthy(isMatch('a/b', 'a/**'));
    expect_truthy(isMatch('a/c', 'a/**'));
    expect_truthy(isMatch('a/x', 'a/**'));
    expect_truthy(isMatch('a/x/y', 'a/**'));
    expect_truthy(isMatch('a/x/y/z', 'a/**'));

    expect_truthy(!isMatch('a', 'a/**/*'));
    expect_truthy(!isMatch('a/', 'a/**/*'));
    expect_truthy(isMatch('a/a', 'a/**/*'));
    expect_truthy(isMatch('a/b', 'a/**/*'));
    expect_truthy(isMatch('a/c', 'a/**/*'));
    expect_truthy(isMatch('a/x', 'a/**/*'));
    expect_truthy(isMatch('a/x/y', 'a/**/*'));
    expect_truthy(isMatch('a/x/y/z', 'a/**/*'));

    expect_truthy(!isMatch('a', 'a/**/**/*'));
    expect_truthy(!isMatch('a/', 'a/**/**/*'));
    expect_truthy(isMatch('a/a', 'a/**/**/*'));
    expect_truthy(isMatch('a/b', 'a/**/**/*'));
    expect_truthy(isMatch('a/c', 'a/**/**/*'));
    expect_truthy(isMatch('a/x', 'a/**/**/*'));
    expect_truthy(isMatch('a/x/y', 'a/**/**/*'));
    expect_truthy(isMatch('a/x/y/z', 'a/**/**/*'));

    expect_truthy(isMatch('a/b/foo/bar/baz.qux', 'a/b/**/bar/**/*.*'));
    expect_truthy(isMatch('a/b/bar/baz.qux', 'a/b/**/bar/**/*.*'));
  });

  test('should support negation patterns', () => {
    expect_truthy(isMatch('a/a', '!a/b'));
    expect_truthy(!isMatch('a/b', '!a/b'));
    expect_truthy(isMatch('a/c', '!a/b'));
    expect_truthy(isMatch('b/a', '!a/b'));
    expect_truthy(isMatch('b/b', '!a/b'));
    expect_truthy(isMatch('b/c', '!a/b'));

    expect_truthy(isMatch('a/a', ['*/*', '!a/b', '!*/c']));
    expect_truthy(isMatch('a/b', ['*/*', '!a/b', '!*/c']));
    expect_truthy(isMatch('a/c', ['*/*', '!a/b', '!*/c']));
    expect_truthy(isMatch('b/a', ['*/*', '!a/b', '!*/c']));
    expect_truthy(isMatch('b/b', ['*/*', '!a/b', '!*/c']));
    expect_truthy(isMatch('b/c', ['*/*', '!a/b', '!*/c']));

    expect_truthy(isMatch('a/a', ['!a/b', '!*/c']));
    expect_truthy(isMatch('a/b', ['!a/b', '!*/c']));
    expect_truthy(isMatch('a/c', ['!a/b', '!*/c']));
    expect_truthy(isMatch('b/a', ['!a/b', '!*/c']));
    expect_truthy(isMatch('b/b', ['!a/b', '!*/c']));
    expect_truthy(isMatch('b/c', ['!a/b', '!*/c']));

    expect_truthy(isMatch('a/a', ['!a/b', '!a/c']));
    expect_truthy(isMatch('a/b', ['!a/b', '!a/c']));
    expect_truthy(isMatch('a/c', ['!a/b', '!a/c']));
    expect_truthy(isMatch('b/a', ['!a/b', '!a/c']));
    expect_truthy(isMatch('b/b', ['!a/b', '!a/c']));
    expect_truthy(isMatch('b/c', ['!a/b', '!a/c']));

    expect_truthy(isMatch('a/a', '!a/(b)'));
    expect_truthy(!isMatch('a/b', '!a/(b)'));
    expect_truthy(isMatch('a/c', '!a/(b)'));
    expect_truthy(isMatch('b/a', '!a/(b)'));
    expect_truthy(isMatch('b/b', '!a/(b)'));
    expect_truthy(isMatch('b/c', '!a/(b)'));

    expect_truthy(isMatch('a/a', '!(a/b)'));
    expect_truthy(!isMatch('a/b', '!(a/b)'));
    expect_truthy(isMatch('a/c', '!(a/b)'));
    expect_truthy(isMatch('b/a', '!(a/b)'));
    expect_truthy(isMatch('b/b', '!(a/b)'));
    expect_truthy(isMatch('b/c', '!(a/b)'));
  });

  test('should work with file extensions', () => {
    expect_truthy(!isMatch('a.txt', 'a/**/*.txt'));
    expect_truthy(isMatch('a/b.txt', 'a/**/*.txt'));
    expect_truthy(isMatch('a/x/y.txt', 'a/**/*.txt'));
    expect_truthy(!isMatch('a/x/y/z', ['a/**/*.txt']));

    expect_truthy(!isMatch('a.txt', 'a/*.txt'));
    expect_truthy(isMatch('a/b.txt', 'a/*.txt'));
    expect_truthy(!isMatch('a/x/y.txt', 'a/*.txt'));
    expect_truthy(!isMatch('a/x/y/z', 'a/*.txt'));

    expect_truthy(isMatch('a.txt', 'a*.txt'));
    expect_truthy(!isMatch('a/b.txt', 'a*.txt'));
    expect_truthy(!isMatch('a/x/y.txt', 'a*.txt'));
    expect_truthy(!isMatch('a/x/y/z', 'a*.txt'));

    expect_truthy(isMatch('a.txt', '*.txt'));
    expect_truthy(!isMatch('a/b.txt', '*.txt'));
    expect_truthy(!isMatch('a/x/y.txt', '*.txt'));
    expect_truthy(!isMatch('a/x/y/z', '*.txt'));
  });

  test('should match one directory level with a single star (*)', () => {
    expect_truthy(!isMatch('/a', '*/'));
    expect_truthy(!isMatch('/a', '*/*/*'));
    expect_truthy(!isMatch('/a', '*/*/*/*'));
    expect_truthy(!isMatch('/a', '*/*/*/*/*'));
    expect_truthy(!isMatch('/a', '/*/'));
    expect_truthy(!isMatch('/a', 'a/*'));
    expect_truthy(!isMatch('/a', 'a/*/*'));
    expect_truthy(!isMatch('/a', 'a/*/*/*'));
    expect_truthy(!isMatch('/a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('/a', 'a/*/a'));
    expect_truthy(!isMatch('/a', 'a/*/b'));
    expect_truthy(!isMatch('/a/', '*'));
    expect_truthy(!isMatch('/a/', '**/*', { strictSlashes: true }));
    expect_truthy(!isMatch('/a/', '*/'));
    expect_truthy(!isMatch('/a/', '*/*', { strictSlashes: true }));
    expect_truthy(!isMatch('/a/', '*/*/*'));
    expect_truthy(!isMatch('/a/', '*/*/*/*'));
    expect_truthy(!isMatch('/a/', '*/*/*/*/*'));
    expect_truthy(!isMatch('/a/', '/*', { strictSlashes: true }));
    expect_truthy(!isMatch('/a/', 'a/*'));
    expect_truthy(!isMatch('/a/', 'a/*/*'));
    expect_truthy(!isMatch('/a/', 'a/*/*/*'));
    expect_truthy(!isMatch('/a/', 'a/*/*/*/*'));
    expect_truthy(!isMatch('/a/', 'a/*/a'));
    expect_truthy(!isMatch('/a/', 'a/*/b'));
    expect_truthy(!isMatch('/ab', '*'));
    expect_truthy(!isMatch('/abc', '*'));
    expect_truthy(!isMatch('/b', '*'));
    expect_truthy(!isMatch('/b', '*/'));
    expect_truthy(!isMatch('/b', '*/*/*'));
    expect_truthy(!isMatch('/b', '*/*/*/*'));
    expect_truthy(!isMatch('/b', '*/*/*/*/*'));
    expect_truthy(!isMatch('/b', '/*/'));
    expect_truthy(!isMatch('/b', 'a/*'));
    expect_truthy(!isMatch('/b', 'a/*/*'));
    expect_truthy(!isMatch('/b', 'a/*/*/*'));
    expect_truthy(!isMatch('/b', 'a/*/*/*/*'));
    expect_truthy(!isMatch('/b', 'a/*/a'));
    expect_truthy(!isMatch('/b', 'a/*/b'));
    expect_truthy(!isMatch('a', '*/'));
    expect_truthy(!isMatch('a', '*/*'));
    expect_truthy(!isMatch('a', '*/*/*'));
    expect_truthy(!isMatch('a', '*/*/*/*'));
    expect_truthy(!isMatch('a', '*/*/*/*/*'));
    expect_truthy(!isMatch('a', '/*'));
    expect_truthy(!isMatch('a', '/*/'));
    expect_truthy(!isMatch('a', 'a/*'));
    expect_truthy(!isMatch('a', 'a/*/*'));
    expect_truthy(!isMatch('a', 'a/*/*/*'));
    expect_truthy(!isMatch('a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a', 'a/*/a'));
    expect_truthy(!isMatch('a', 'a/*/b'));
    expect_truthy(!isMatch('a/', '*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', '**/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', '*/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', '*/*/*/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', '*/*/*/*/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', '/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', '/*/', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', 'a/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', 'a/*/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', 'a/*/*/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', 'a/*/*/*/*', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', 'a/*/a', { strictSlashes: true }));
    expect_truthy(!isMatch('a/', 'a/*/b', { strictSlashes: true }));
    expect_truthy(!isMatch('a/a', '*'));
    expect_truthy(!isMatch('a/a', '*/'));
    expect_truthy(!isMatch('a/a', '*/*/*'));
    expect_truthy(!isMatch('a/a', '*/*/*/*'));
    expect_truthy(!isMatch('a/a', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/a', '/*'));
    expect_truthy(!isMatch('a/a', '/*/'));
    expect_truthy(!isMatch('a/a', 'a/*/*'));
    expect_truthy(!isMatch('a/a', 'a/*/*/*'));
    expect_truthy(!isMatch('a/a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/a', 'a/*/a'));
    expect_truthy(!isMatch('a/a', 'a/*/b'));
    expect_truthy(!isMatch('a/a/a', '*'));
    expect_truthy(!isMatch('a/a/a', '*/'));
    expect_truthy(!isMatch('a/a/a', '*/*'));
    expect_truthy(!isMatch('a/a/a', '*/*/*/*'));
    expect_truthy(!isMatch('a/a/a', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/a/a', '/*'));
    expect_truthy(!isMatch('a/a/a', '/*/'));
    expect_truthy(!isMatch('a/a/a', 'a/*'));
    expect_truthy(!isMatch('a/a/a', 'a/*/*/*'));
    expect_truthy(!isMatch('a/a/a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/a/a', 'a/*/b'));
    expect_truthy(!isMatch('a/a/a/a', '*'));
    expect_truthy(!isMatch('a/a/a/a', '*/'));
    expect_truthy(!isMatch('a/a/a/a', '*/*'));
    expect_truthy(!isMatch('a/a/a/a', '*/*/*'));
    expect_truthy(!isMatch('a/a/a/a', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/a/a/a', '/*'));
    expect_truthy(!isMatch('a/a/a/a', '/*/'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/*'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/a'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/b'));
    expect_truthy(!isMatch('a/a/a/a/a', '*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*/*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', '/*'));
    expect_truthy(!isMatch('a/a/a/a/a', '/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/*/*'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/a'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/b'));
    expect_truthy(!isMatch('a/a/b', '*'));
    expect_truthy(!isMatch('a/a/b', '*/'));
    expect_truthy(!isMatch('a/a/b', '*/*'));
    expect_truthy(!isMatch('a/a/b', '*/*/*/*'));
    expect_truthy(!isMatch('a/a/b', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/a/b', '/*'));
    expect_truthy(!isMatch('a/a/b', '/*/'));
    expect_truthy(!isMatch('a/a/b', 'a/*'));
    expect_truthy(!isMatch('a/a/b', 'a/*/*/*'));
    expect_truthy(!isMatch('a/a/b', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/a/b', 'a/*/a'));
    expect_truthy(!isMatch('a/b', '*'));
    expect_truthy(!isMatch('a/b', '*/'));
    expect_truthy(!isMatch('a/b', '*/*/*/*'));
    expect_truthy(!isMatch('a/b', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/b', '/*'));
    expect_truthy(!isMatch('a/b', '/*/'));
    expect_truthy(!isMatch('a/b', 'a/*/*'));
    expect_truthy(!isMatch('a/b', 'a/*/*/*'));
    expect_truthy(!isMatch('a/b', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/b', 'a/*/a'));
    expect_truthy(!isMatch('a/b', 'a/*/b'));
    expect_truthy(!isMatch('a/c', '*'));
    expect_truthy(!isMatch('a/c', '*/'));
    expect_truthy(!isMatch('a/c', '*/*/*/*'));
    expect_truthy(!isMatch('a/c', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/c', '/*'));
    expect_truthy(!isMatch('a/c', '/*/'));
    expect_truthy(!isMatch('a/c', 'a/*/*'));
    expect_truthy(!isMatch('a/c', 'a/*/*/*'));
    expect_truthy(!isMatch('a/c', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/c', 'a/*/a'));
    expect_truthy(!isMatch('a/c', 'a/*/b'));
    expect_truthy(!isMatch('a/x', '*'));
    expect_truthy(!isMatch('a/x', '*/'));
    expect_truthy(!isMatch('a/x', '*/*/*/*'));
    expect_truthy(!isMatch('a/x', '*/*/*/*/*'));
    expect_truthy(!isMatch('a/x', '/*'));
    expect_truthy(!isMatch('a/x', '/*/'));
    expect_truthy(!isMatch('a/x', 'a/*/*'));
    expect_truthy(!isMatch('a/x', 'a/*/*/*'));
    expect_truthy(!isMatch('a/x', 'a/*/*/*/*'));
    expect_truthy(!isMatch('a/x', 'a/*/a'));
    expect_truthy(!isMatch('a/x', 'a/*/b'));
    expect_truthy(!isMatch('b', '*/'));
    expect_truthy(!isMatch('b', '*/*'));
    expect_truthy(!isMatch('b', '*/*/*/*'));
    expect_truthy(!isMatch('b', '*/*/*/*/*'));
    expect_truthy(!isMatch('b', '/*'));
    expect_truthy(!isMatch('b', '/*/'));
    expect_truthy(!isMatch('b', 'a/*'));
    expect_truthy(!isMatch('b', 'a/*/*'));
    expect_truthy(!isMatch('b', 'a/*/*/*'));
    expect_truthy(!isMatch('b', 'a/*/*/*/*'));
    expect_truthy(!isMatch('b', 'a/*/a'));
    expect_truthy(!isMatch('b', 'a/*/b'));
    expect_truthy(!isMatch('x/y', '*'));
    expect_truthy(!isMatch('x/y', '*/'));
    expect_truthy(!isMatch('x/y', '*/*/*'));
    expect_truthy(!isMatch('x/y', '*/*/*/*'));
    expect_truthy(!isMatch('x/y', '*/*/*/*/*'));
    expect_truthy(!isMatch('x/y', '/*'));
    expect_truthy(!isMatch('x/y', '/*/'));
    expect_truthy(!isMatch('x/y', 'a/*'));
    expect_truthy(!isMatch('x/y', 'a/*/*'));
    expect_truthy(!isMatch('x/y', 'a/*/*/*'));
    expect_truthy(!isMatch('x/y', 'a/*/*/*/*'));
    expect_truthy(!isMatch('x/y', 'a/*/a'));
    expect_truthy(!isMatch('x/y', 'a/*/b'));
    expect_truthy(!isMatch('z/z', '*'));
    expect_truthy(!isMatch('z/z', '*/'));
    expect_truthy(!isMatch('z/z', '*/*/*/*'));
    expect_truthy(!isMatch('z/z', '*/*/*/*/*'));
    expect_truthy(!isMatch('z/z', '/*'));
    expect_truthy(!isMatch('z/z', '/*/'));
    expect_truthy(!isMatch('z/z', 'a/*'));
    expect_truthy(!isMatch('z/z', 'a/*/*'));
    expect_truthy(!isMatch('z/z', 'a/*/*/*'));
    expect_truthy(!isMatch('z/z', 'a/*/*/*/*'));
    expect_truthy(!isMatch('z/z', 'a/*/a'));
    expect_truthy(!isMatch('z/z', 'a/*/b'));
    expect_truthy(isMatch('/a', '**/*'));
    expect_truthy(isMatch('/a', '*/*'));
    expect_truthy(isMatch('/a', '/*'));
    expect_truthy(isMatch('/a/', '**/*{,/}'));
    expect_truthy(isMatch('/a/', '*/*'));
    expect_truthy(isMatch('/a/', '*/*{,/}'));
    expect_truthy(isMatch('/a/', '/*'));
    expect_truthy(isMatch('/a/', '/*/'));
    expect_truthy(isMatch('/a/', '/*{,/}'));
    expect_truthy(isMatch('/b', '**/*'));
    expect_truthy(isMatch('/b', '*/*'));
    expect_truthy(isMatch('/b', '/*'));
    expect_truthy(isMatch('a', '*'));
    expect_truthy(isMatch('a', '**/*'));
    expect_truthy(isMatch('a/', '**/*{,/}'));
    expect_truthy(isMatch('a/', '*/'));
    expect_truthy(isMatch('a/', '*{,/}'));
    expect_truthy(isMatch('a/a', '**/*'));
    expect_truthy(isMatch('a/a', '*/*'));
    expect_truthy(isMatch('a/a', 'a/*'));
    expect_truthy(isMatch('a/a/a', '**/*'));
    expect_truthy(isMatch('a/a/a', '*/*/*'));
    expect_truthy(isMatch('a/a/a', 'a/*/*'));
    expect_truthy(isMatch('a/a/a', 'a/*/a'));
    expect_truthy(isMatch('a/a/a/a', '**/*'));
    expect_truthy(isMatch('a/a/a/a', '*/*/*/*'));
    expect_truthy(isMatch('a/a/a/a', 'a/*/*/*'));
    expect_truthy(isMatch('a/a/a/a/a', '**/*'));
    expect_truthy(isMatch('a/a/a/a/a', '*/*/*/*/*'));
    expect_truthy(isMatch('a/a/a/a/a', 'a/*/*/*/*'));
    expect_truthy(isMatch('a/a/b', '**/*'));
    expect_truthy(isMatch('a/a/b', 'a/*/*'));
    expect_truthy(isMatch('a/a/b', 'a/*/b'));
    expect_truthy(isMatch('a/b', '**/*'));
    expect_truthy(isMatch('a/b', '*/*'));
    expect_truthy(isMatch('a/b', 'a/*'));
    expect_truthy(isMatch('a/c', '**/*'));
    expect_truthy(isMatch('a/c', '*/*'));
    expect_truthy(isMatch('a/c', 'a/*'));
    expect_truthy(isMatch('a/x', '**/*'));
    expect_truthy(isMatch('a/x', '*/*'));
    expect_truthy(isMatch('a/x', 'a/*'));
    expect_truthy(isMatch('b', '*'));
    expect_truthy(isMatch('b', '**/*'));
    expect_truthy(isMatch('x/y', '**/*'));
    expect_truthy(isMatch('x/y', '*/*'));
    expect_truthy(isMatch('z/z', '**/*'));
    expect_truthy(isMatch('z/z', '*/*'));
  });

  test('should match one or more directories with a globstar', () => {
    expect_truthy(!isMatch('a/', '**/a'));
    expect_truthy(!isMatch('/a/', '**/a'));
    expect_truthy(!isMatch('a/a/', '**/a'));
    expect_truthy(!isMatch('/a/a/', '**/a'));
    expect_truthy(!isMatch('a/a/a/', '**/a'));

    expect_truthy(isMatch('a', '**/a'));
    expect_truthy(isMatch('a/a', '**/a'));
    expect_truthy(isMatch('a/a/a', '**/a'));
    expect_truthy(isMatch('/a', '**/a'));
    expect_truthy(isMatch('a/a/', '**/a/*{,/}'));
    expect_truthy(!isMatch('a/a/', '**/a/*', { strictSlashes: true }));
    expect_truthy(isMatch('/a/a', '**/a'));

    expect_truthy(isMatch('a', 'a/**'));
    expect_truthy(!isMatch('/a', 'a/**'));
    expect_truthy(!isMatch('/a/', 'a/**'));
    expect_truthy(!isMatch('/a/a', 'a/**'));
    expect_truthy(!isMatch('/a/a/', 'a/**'));
    expect_truthy(isMatch('/a', '/a/**'));
    expect_truthy(isMatch('/a/', '/a/**'));
    expect_truthy(isMatch('/a/a', '/a/**'));
    expect_truthy(isMatch('/a/a/', '/a/**'));
    expect_truthy(isMatch('a/', 'a/**'));
    expect_truthy(isMatch('a/a', 'a/**'));
    expect_truthy(isMatch('a/a/', 'a/**'));
    expect_truthy(isMatch('a/a/a', 'a/**'));
    expect_truthy(isMatch('a/a/a/', 'a/**'));

    expect_truthy(isMatch('a', '**/a/**'));
    expect_truthy(isMatch('/a', '**/a/**'));
    expect_truthy(isMatch('/a/', '**/a/**'));
    expect_truthy(isMatch('/a/a', '**/a/**'));
    expect_truthy(isMatch('/a/a/', '**/a/**'));
    expect_truthy(isMatch('a/', '**/a/**'));
    expect_truthy(isMatch('a/a', '**/a/**'));
    expect_truthy(isMatch('a/a/', '**/a/**'));
    expect_truthy(isMatch('a/a/a', '**/a/**'));
    expect_truthy(isMatch('a/a/a/', '**/a/**'));
  });

  test('should match one or more characters', () => {
    expect_truthy(isMatch('a', '*'));
    expect_truthy(isMatch('aa', '*'));
    expect_truthy(isMatch('aaa', '*'));
    expect_truthy(isMatch('aaaa', '*'));
    expect_truthy(isMatch('ab', '*'));
    expect_truthy(isMatch('b', '*'));
    expect_truthy(isMatch('bb', '*'));
    expect_truthy(isMatch('c', '*'));
    expect_truthy(isMatch('cc', '*'));
    expect_truthy(isMatch('cac', '*'));
    expect_truthy(!isMatch('a/a', '*'));
    expect_truthy(!isMatch('a/b', '*'));
    expect_truthy(!isMatch('a/c', '*'));
    expect_truthy(!isMatch('a/x', '*'));
    expect_truthy(!isMatch('a/a/a', '*'));
    expect_truthy(!isMatch('a/a/b', '*'));
    expect_truthy(!isMatch('a/a/a/a', '*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*'));
    expect_truthy(!isMatch('x/y', '*'));
    expect_truthy(!isMatch('z/z', '*'));

    expect_truthy(isMatch('a', 'a*'));
    expect_truthy(isMatch('aa', 'a*'));
    expect_truthy(isMatch('aaa', 'a*'));
    expect_truthy(isMatch('aaaa', 'a*'));
    expect_truthy(isMatch('ab', 'a*'));
    expect_truthy(!isMatch('b', 'a*'));
    expect_truthy(!isMatch('bb', 'a*'));
    expect_truthy(!isMatch('c', 'a*'));
    expect_truthy(!isMatch('cc', 'a*'));
    expect_truthy(!isMatch('cac', 'a*'));
    expect_truthy(!isMatch('a/a', 'a*'));
    expect_truthy(!isMatch('a/b', 'a*'));
    expect_truthy(!isMatch('a/c', 'a*'));
    expect_truthy(!isMatch('a/x', 'a*'));
    expect_truthy(!isMatch('a/a/a', 'a*'));
    expect_truthy(!isMatch('a/a/b', 'a*'));
    expect_truthy(!isMatch('a/a/a/a', 'a*'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a*'));
    expect_truthy(!isMatch('x/y', 'a*'));
    expect_truthy(!isMatch('z/z', 'a*'));

    expect_truthy(!isMatch('a', '*b'));
    expect_truthy(!isMatch('aa', '*b'));
    expect_truthy(!isMatch('aaa', '*b'));
    expect_truthy(!isMatch('aaaa', '*b'));
    expect_truthy(isMatch('ab', '*b'));
    expect_truthy(isMatch('b', '*b'));
    expect_truthy(isMatch('bb', '*b'));
    expect_truthy(!isMatch('c', '*b'));
    expect_truthy(!isMatch('cc', '*b'));
    expect_truthy(!isMatch('cac', '*b'));
    expect_truthy(!isMatch('a/a', '*b'));
    expect_truthy(!isMatch('a/b', '*b'));
    expect_truthy(!isMatch('a/c', '*b'));
    expect_truthy(!isMatch('a/x', '*b'));
    expect_truthy(!isMatch('a/a/a', '*b'));
    expect_truthy(!isMatch('a/a/b', '*b'));
    expect_truthy(!isMatch('a/a/a/a', '*b'));
    expect_truthy(!isMatch('a/a/a/a/a', '*b'));
    expect_truthy(!isMatch('x/y', '*b'));
    expect_truthy(!isMatch('z/z', '*b'));
  });

  test('should match one or zero characters', () => {
    expect_truthy(isMatch('a', '*'));
    expect_truthy(isMatch('aa', '*'));
    expect_truthy(isMatch('aaa', '*'));
    expect_truthy(isMatch('aaaa', '*'));
    expect_truthy(isMatch('ab', '*'));
    expect_truthy(isMatch('b', '*'));
    expect_truthy(isMatch('bb', '*'));
    expect_truthy(isMatch('c', '*'));
    expect_truthy(isMatch('cc', '*'));
    expect_truthy(isMatch('cac', '*'));
    expect_truthy(!isMatch('a/a', '*'));
    expect_truthy(!isMatch('a/b', '*'));
    expect_truthy(!isMatch('a/c', '*'));
    expect_truthy(!isMatch('a/x', '*'));
    expect_truthy(!isMatch('a/a/a', '*'));
    expect_truthy(!isMatch('a/a/b', '*'));
    expect_truthy(!isMatch('a/a/a/a', '*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*'));
    expect_truthy(!isMatch('x/y', '*'));
    expect_truthy(!isMatch('z/z', '*'));

    expect_truthy(isMatch('a', '*a*'));
    expect_truthy(isMatch('aa', '*a*'));
    expect_truthy(isMatch('aaa', '*a*'));
    expect_truthy(isMatch('aaaa', '*a*'));
    expect_truthy(isMatch('ab', '*a*'));
    expect_truthy(!isMatch('b', '*a*'));
    expect_truthy(!isMatch('bb', '*a*'));
    expect_truthy(!isMatch('c', '*a*'));
    expect_truthy(!isMatch('cc', '*a*'));
    expect_truthy(isMatch('cac', '*a*'));
    expect_truthy(!isMatch('a/a', '*a*'));
    expect_truthy(!isMatch('a/b', '*a*'));
    expect_truthy(!isMatch('a/c', '*a*'));
    expect_truthy(!isMatch('a/x', '*a*'));
    expect_truthy(!isMatch('a/a/a', '*a*'));
    expect_truthy(!isMatch('a/a/b', '*a*'));
    expect_truthy(!isMatch('a/a/a/a', '*a*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*a*'));
    expect_truthy(!isMatch('x/y', '*a*'));
    expect_truthy(!isMatch('z/z', '*a*'));

    expect_truthy(!isMatch('a', '*b*'));
    expect_truthy(!isMatch('aa', '*b*'));
    expect_truthy(!isMatch('aaa', '*b*'));
    expect_truthy(!isMatch('aaaa', '*b*'));
    expect_truthy(isMatch('ab', '*b*'));
    expect_truthy(isMatch('b', '*b*'));
    expect_truthy(isMatch('bb', '*b*'));
    expect_truthy(!isMatch('c', '*b*'));
    expect_truthy(!isMatch('cc', '*b*'));
    expect_truthy(!isMatch('cac', '*b*'));
    expect_truthy(!isMatch('a/a', '*b*'));
    expect_truthy(!isMatch('a/b', '*b*'));
    expect_truthy(!isMatch('a/c', '*b*'));
    expect_truthy(!isMatch('a/x', '*b*'));
    expect_truthy(!isMatch('a/a/a', '*b*'));
    expect_truthy(!isMatch('a/a/b', '*b*'));
    expect_truthy(!isMatch('a/a/a/a', '*b*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*b*'));
    expect_truthy(!isMatch('x/y', '*b*'));
    expect_truthy(!isMatch('z/z', '*b*'));

    expect_truthy(!isMatch('a', '*c*'));
    expect_truthy(!isMatch('aa', '*c*'));
    expect_truthy(!isMatch('aaa', '*c*'));
    expect_truthy(!isMatch('aaaa', '*c*'));
    expect_truthy(!isMatch('ab', '*c*'));
    expect_truthy(!isMatch('b', '*c*'));
    expect_truthy(!isMatch('bb', '*c*'));
    expect_truthy(isMatch('c', '*c*'));
    expect_truthy(isMatch('cc', '*c*'));
    expect_truthy(isMatch('cac', '*c*'));
    expect_truthy(!isMatch('a/a', '*c*'));
    expect_truthy(!isMatch('a/b', '*c*'));
    expect_truthy(!isMatch('a/c', '*c*'));
    expect_truthy(!isMatch('a/x', '*c*'));
    expect_truthy(!isMatch('a/a/a', '*c*'));
    expect_truthy(!isMatch('a/a/b', '*c*'));
    expect_truthy(!isMatch('a/a/a/a', '*c*'));
    expect_truthy(!isMatch('a/a/a/a/a', '*c*'));
    expect_truthy(!isMatch('x/y', '*c*'));
    expect_truthy(!isMatch('z/z', '*c*'));
  });

  test('should respect trailing slashes on paterns', () => {
    expect_truthy(!isMatch('a', '*/'));
    expect_truthy(isMatch('a/', '*/'));
    expect_truthy(!isMatch('b', '*/'));
    expect_truthy(isMatch('b/', '*/'));
    expect_truthy(!isMatch('a/a', '*/'));
    expect_truthy(!isMatch('a/a/', '*/'));
    expect_truthy(!isMatch('a/b', '*/'));
    expect_truthy(!isMatch('a/b/', '*/'));
    expect_truthy(!isMatch('a/c', '*/'));
    expect_truthy(!isMatch('a/c/', '*/'));
    expect_truthy(!isMatch('a/x', '*/'));
    expect_truthy(!isMatch('a/x/', '*/'));
    expect_truthy(!isMatch('a/a/a', '*/'));
    expect_truthy(!isMatch('a/a/b', '*/'));
    expect_truthy(!isMatch('a/a/b/', '*/'));
    expect_truthy(!isMatch('a/a/a/', '*/'));
    expect_truthy(!isMatch('a/a/a/a', '*/'));
    expect_truthy(!isMatch('a/a/a/a/', '*/'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/'));
    expect_truthy(!isMatch('a/a/a/a/a/', '*/'));
    expect_truthy(!isMatch('x/y', '*/'));
    expect_truthy(!isMatch('z/z', '*/'));
    expect_truthy(!isMatch('x/y/', '*/'));
    expect_truthy(!isMatch('z/z/', '*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', '*/'));

    expect_truthy(!isMatch('a', '*/*/'));
    expect_truthy(!isMatch('a/', '*/*/'));
    expect_truthy(!isMatch('b', '*/*/'));
    expect_truthy(!isMatch('b/', '*/*/'));
    expect_truthy(!isMatch('a/a', '*/*/'));
    expect_truthy(isMatch('a/a/', '*/*/'));
    expect_truthy(!isMatch('a/b', '*/*/'));
    expect_truthy(isMatch('a/b/', '*/*/'));
    expect_truthy(!isMatch('a/c', '*/*/'));
    expect_truthy(isMatch('a/c/', '*/*/'));
    expect_truthy(!isMatch('a/x', '*/*/'));
    expect_truthy(isMatch('a/x/', '*/*/'));
    expect_truthy(!isMatch('a/a/a', '*/*/'));
    expect_truthy(!isMatch('a/a/b', '*/*/'));
    expect_truthy(!isMatch('a/a/b/', '*/*/'));
    expect_truthy(!isMatch('a/a/a/', '*/*/'));
    expect_truthy(!isMatch('a/a/a/a', '*/*/'));
    expect_truthy(!isMatch('a/a/a/a/', '*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a/', '*/*/'));
    expect_truthy(!isMatch('x/y', '*/*/'));
    expect_truthy(!isMatch('z/z', '*/*/'));
    expect_truthy(isMatch('x/y/', '*/*/'));
    expect_truthy(isMatch('z/z/', '*/*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', '*/*/'));

    expect_truthy(!isMatch('a', '*/*/*/'));
    expect_truthy(!isMatch('a/', '*/*/*/'));
    expect_truthy(!isMatch('b', '*/*/*/'));
    expect_truthy(!isMatch('b/', '*/*/*/'));
    expect_truthy(!isMatch('a/a', '*/*/*/'));
    expect_truthy(!isMatch('a/a/', '*/*/*/'));
    expect_truthy(!isMatch('a/b', '*/*/*/'));
    expect_truthy(!isMatch('a/b/', '*/*/*/'));
    expect_truthy(!isMatch('a/c', '*/*/*/'));
    expect_truthy(!isMatch('a/c/', '*/*/*/'));
    expect_truthy(!isMatch('a/x', '*/*/*/'));
    expect_truthy(!isMatch('a/x/', '*/*/*/'));
    expect_truthy(!isMatch('a/a/a', '*/*/*/'));
    expect_truthy(!isMatch('a/a/b', '*/*/*/'));
    expect_truthy(isMatch('a/a/b/', '*/*/*/'));
    expect_truthy(isMatch('a/a/a/', '*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a', '*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/', '*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a/', '*/*/*/'));
    expect_truthy(!isMatch('x/y', '*/*/*/'));
    expect_truthy(!isMatch('z/z', '*/*/*/'));
    expect_truthy(!isMatch('x/y/', '*/*/*/'));
    expect_truthy(!isMatch('z/z/', '*/*/*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', '*/*/*/'));

    expect_truthy(!isMatch('a', '*/*/*/*/'));
    expect_truthy(!isMatch('a/', '*/*/*/*/'));
    expect_truthy(!isMatch('b', '*/*/*/*/'));
    expect_truthy(!isMatch('b/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/b', '*/*/*/*/'));
    expect_truthy(!isMatch('a/b/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/c', '*/*/*/*/'));
    expect_truthy(!isMatch('a/c/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/x', '*/*/*/*/'));
    expect_truthy(!isMatch('a/x/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a/b', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a/b/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a', '*/*/*/*/'));
    expect_truthy(isMatch('a/a/a/a/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a/', '*/*/*/*/'));
    expect_truthy(!isMatch('x/y', '*/*/*/*/'));
    expect_truthy(!isMatch('z/z', '*/*/*/*/'));
    expect_truthy(!isMatch('x/y/', '*/*/*/*/'));
    expect_truthy(!isMatch('z/z/', '*/*/*/*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', '*/*/*/*/'));

    expect_truthy(!isMatch('a', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('b', '*/*/*/*/*/'));
    expect_truthy(!isMatch('b/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/b', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/b/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/c', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/c/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/x', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/x/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/b', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/b/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', '*/*/*/*/*/'));
    expect_truthy(isMatch('a/a/a/a/a/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('x/y', '*/*/*/*/*/'));
    expect_truthy(!isMatch('z/z', '*/*/*/*/*/'));
    expect_truthy(!isMatch('x/y/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('z/z/', '*/*/*/*/*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', '*/*/*/*/*/'));

    expect_truthy(!isMatch('a', 'a/*/'));
    expect_truthy(!isMatch('a/', 'a/*/'));
    expect_truthy(!isMatch('b', 'a/*/'));
    expect_truthy(!isMatch('b/', 'a/*/'));
    expect_truthy(!isMatch('a/a', 'a/*/'));
    expect_truthy(isMatch('a/a/', 'a/*/'));
    expect_truthy(!isMatch('a/b', 'a/*/'));
    expect_truthy(isMatch('a/b/', 'a/*/'));
    expect_truthy(!isMatch('a/c', 'a/*/'));
    expect_truthy(isMatch('a/c/', 'a/*/'));
    expect_truthy(!isMatch('a/x', 'a/*/'));
    expect_truthy(isMatch('a/x/', 'a/*/'));
    expect_truthy(!isMatch('a/a/a', 'a/*/'));
    expect_truthy(!isMatch('a/a/b', 'a/*/'));
    expect_truthy(!isMatch('a/a/b/', 'a/*/'));
    expect_truthy(!isMatch('a/a/a/', 'a/*/'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/'));
    expect_truthy(!isMatch('a/a/a/a/', 'a/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/'));
    expect_truthy(!isMatch('a/a/a/a/a/', 'a/*/'));
    expect_truthy(!isMatch('x/y', 'a/*/'));
    expect_truthy(!isMatch('z/z', 'a/*/'));
    expect_truthy(!isMatch('x/y/', 'a/*/'));
    expect_truthy(!isMatch('z/z/', 'a/*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', 'a/*/'));

    expect_truthy(!isMatch('a', 'a/*/*/'));
    expect_truthy(!isMatch('a/', 'a/*/*/'));
    expect_truthy(!isMatch('b', 'a/*/*/'));
    expect_truthy(!isMatch('b/', 'a/*/*/'));
    expect_truthy(!isMatch('a/a', 'a/*/*/'));
    expect_truthy(!isMatch('a/a/', 'a/*/*/'));
    expect_truthy(!isMatch('a/b', 'a/*/*/'));
    expect_truthy(!isMatch('a/b/', 'a/*/*/'));
    expect_truthy(!isMatch('a/c', 'a/*/*/'));
    expect_truthy(!isMatch('a/c/', 'a/*/*/'));
    expect_truthy(!isMatch('a/x', 'a/*/*/'));
    expect_truthy(!isMatch('a/x/', 'a/*/*/'));
    expect_truthy(!isMatch('a/a/a', 'a/*/*/'));
    expect_truthy(!isMatch('a/a/b', 'a/*/*/'));
    expect_truthy(isMatch('a/a/b/', 'a/*/*/'));
    expect_truthy(isMatch('a/a/a/', 'a/*/*/'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/', 'a/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a/', 'a/*/*/'));
    expect_truthy(!isMatch('x/y', 'a/*/*/'));
    expect_truthy(!isMatch('z/z', 'a/*/*/'));
    expect_truthy(!isMatch('x/y/', 'a/*/*/'));
    expect_truthy(!isMatch('z/z/', 'a/*/*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', 'a/*/*/'));

    expect_truthy(!isMatch('a', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/', 'a/*/*/*/'));
    expect_truthy(!isMatch('b', 'a/*/*/*/'));
    expect_truthy(!isMatch('b/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/b', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/b/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/c', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/c/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/x', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/x/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a/a', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a/b', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a/b/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/*/*/'));
    expect_truthy(isMatch('a/a/a/a/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a/', 'a/*/*/*/'));
    expect_truthy(!isMatch('x/y', 'a/*/*/*/'));
    expect_truthy(!isMatch('z/z', 'a/*/*/*/'));
    expect_truthy(!isMatch('x/y/', 'a/*/*/*/'));
    expect_truthy(!isMatch('z/z/', 'a/*/*/*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', 'a/*/*/*/'));

    expect_truthy(!isMatch('a', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('b', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('b/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/b', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/b/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/c', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/c/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/x', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/x/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/b', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/b/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/*/*/*/'));
    expect_truthy(isMatch('a/a/a/a/a/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('x/y', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('z/z', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('x/y/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('z/z/', 'a/*/*/*/*/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', 'a/*/*/*/*/'));

    expect_truthy(!isMatch('a', 'a/*/a/'));
    expect_truthy(!isMatch('a/', 'a/*/a/'));
    expect_truthy(!isMatch('b', 'a/*/a/'));
    expect_truthy(!isMatch('b/', 'a/*/a/'));
    expect_truthy(!isMatch('a/a', 'a/*/a/'));
    expect_truthy(!isMatch('a/a/', 'a/*/a/'));
    expect_truthy(!isMatch('a/b', 'a/*/a/'));
    expect_truthy(!isMatch('a/b/', 'a/*/a/'));
    expect_truthy(!isMatch('a/c', 'a/*/a/'));
    expect_truthy(!isMatch('a/c/', 'a/*/a/'));
    expect_truthy(!isMatch('a/x', 'a/*/a/'));
    expect_truthy(!isMatch('a/x/', 'a/*/a/'));
    expect_truthy(!isMatch('a/a/a', 'a/*/a/'));
    expect_truthy(!isMatch('a/a/b', 'a/*/a/'));
    expect_truthy(!isMatch('a/a/b/', 'a/*/a/'));
    expect_truthy(isMatch('a/a/a/', 'a/*/a/'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/a/'));
    expect_truthy(!isMatch('a/a/a/a/', 'a/*/a/'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/a/'));
    expect_truthy(!isMatch('a/a/a/a/a/', 'a/*/a/'));
    expect_truthy(!isMatch('x/y', 'a/*/a/'));
    expect_truthy(!isMatch('z/z', 'a/*/a/'));
    expect_truthy(!isMatch('x/y/', 'a/*/a/'));
    expect_truthy(!isMatch('z/z/', 'a/*/a/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', 'a/*/a/'));

    expect_truthy(!isMatch('a', 'a/*/b/'));
    expect_truthy(!isMatch('a/', 'a/*/b/'));
    expect_truthy(!isMatch('b', 'a/*/b/'));
    expect_truthy(!isMatch('b/', 'a/*/b/'));
    expect_truthy(!isMatch('a/a', 'a/*/b/'));
    expect_truthy(!isMatch('a/a/', 'a/*/b/'));
    expect_truthy(!isMatch('a/b', 'a/*/b/'));
    expect_truthy(!isMatch('a/b/', 'a/*/b/'));
    expect_truthy(!isMatch('a/c', 'a/*/b/'));
    expect_truthy(!isMatch('a/c/', 'a/*/b/'));
    expect_truthy(!isMatch('a/x', 'a/*/b/'));
    expect_truthy(!isMatch('a/x/', 'a/*/b/'));
    expect_truthy(!isMatch('a/a/a', 'a/*/b/'));
    expect_truthy(!isMatch('a/a/b', 'a/*/b/'));
    expect_truthy(isMatch('a/a/b/', 'a/*/b/'));
    expect_truthy(!isMatch('a/a/a/', 'a/*/b/'));
    expect_truthy(!isMatch('a/a/a/a', 'a/*/b/'));
    expect_truthy(!isMatch('a/a/a/a/', 'a/*/b/'));
    expect_truthy(!isMatch('a/a/a/a/a', 'a/*/b/'));
    expect_truthy(!isMatch('a/a/a/a/a/', 'a/*/b/'));
    expect_truthy(!isMatch('x/y', 'a/*/b/'));
    expect_truthy(!isMatch('z/z', 'a/*/b/'));
    expect_truthy(!isMatch('x/y/', 'a/*/b/'));
    expect_truthy(!isMatch('z/z/', 'a/*/b/'));
    expect_truthy(!isMatch('a/b/c/.d/e/', 'a/*/b/'));
  });

  test('should match a literal star when escaped', () => {
    expect_truthy(!isMatch('.md', '\\*'));
    expect_truthy(!isMatch('a**a.md', '\\*'));
    expect_truthy(!isMatch('**a.md', '\\*'));
    expect_truthy(!isMatch('**/a.md', '\\*'));
    expect_truthy(!isMatch('**.md', '\\*'));
    expect_truthy(!isMatch('.md', '\\*'));
    expect_truthy(isMatch('*', '\\*'));
    expect_truthy(!isMatch('**', '\\*'));
    expect_truthy(!isMatch('*.md', '\\*'));

    expect_truthy(!isMatch('.md', '\\*.md'));
    expect_truthy(!isMatch('a**a.md', '\\*.md'));
    expect_truthy(!isMatch('**a.md', '\\*.md'));
    expect_truthy(!isMatch('**/a.md', '\\*.md'));
    expect_truthy(!isMatch('**.md', '\\*.md'));
    expect_truthy(!isMatch('.md', '\\*.md'));
    expect_truthy(!isMatch('*', '\\*.md'));
    expect_truthy(!isMatch('**', '\\*.md'));
    expect_truthy(isMatch('*.md', '\\*.md'));

    expect_truthy(!isMatch('.md', '\\**.md'));
    expect_truthy(!isMatch('a**a.md', '\\**.md'));
    expect_truthy(isMatch('**a.md', '\\**.md'));
    expect_truthy(!isMatch('**/a.md', '\\**.md'));
    expect_truthy(isMatch('**.md', '\\**.md'));
    expect_truthy(!isMatch('.md', '\\**.md'));
    expect_truthy(!isMatch('*', '\\**.md'));
    expect_truthy(!isMatch('**', '\\**.md'));
    expect_truthy(isMatch('*.md', '\\**.md'));

    expect_truthy(!isMatch('.md', 'a\\**.md'));
    expect_truthy(isMatch('a**a.md', 'a\\**.md'));
    expect_truthy(!isMatch('**a.md', 'a\\**.md'));
    expect_truthy(!isMatch('**/a.md', 'a\\**.md'));
    expect_truthy(!isMatch('**.md', 'a\\**.md'));
    expect_truthy(!isMatch('.md', 'a\\**.md'));
    expect_truthy(!isMatch('*', 'a\\**.md'));
    expect_truthy(!isMatch('**', 'a\\**.md'));
    expect_truthy(!isMatch('*.md', 'a\\**.md'));
  });

  test('should match file paths', () => {
    expect_truthy(!isMatch('a/.b', 'a/**/z/*.md'));
    expect_truthy(!isMatch('a/b/c/j/e/z/c.txt', 'a/**/j/**/z/*.md'));
    expect_truthy(!isMatch('a/b/z/.a', 'a/**/z/*.a'));
    expect_truthy(!isMatch('a/b/z/.a', 'a/*/z/*.a'));
    expect_truthy(!isMatch('foo.txt', '*/*.txt'));
    expect_truthy(isMatch('a/.b', 'a/.*'));
    expect_truthy(isMatch('a/b/c/d/e/j/n/p/o/z/c.md', 'a/**/j/**/z/*.md'));
    expect_truthy(isMatch('a/b/c/d/e/z/c.md', 'a/**/z/*.md'));
    expect_truthy(isMatch('a/b/c/xyz.md', 'a/b/c/*.md'));
    expect_truthy(isMatch('a/b/z/.a', 'a/*/z/.a'));
    expect_truthy(isMatch('a/bb.bb/aa/b.b/aa/c/xyz.md', 'a/**/c/*.md'));
    expect_truthy(isMatch('a/bb.bb/aa/bb/aa/c/xyz.md', 'a/**/c/*.md'));
    expect_truthy(isMatch('a/bb.bb/c/xyz.md', 'a/*/c/*.md'));
    expect_truthy(isMatch('a/bb/c/xyz.md', 'a/*/c/*.md'));
    expect_truthy(isMatch('a/bbbb/c/xyz.md', 'a/*/c/*.md'));
    expect_truthy(isMatch('foo.txt', '**/foo.txt'));
    expect_truthy(isMatch('foo/bar.txt', '**/*.txt'));
    expect_truthy(isMatch('foo/bar/baz.txt', '**/*.txt'));
  });

  test('should match paths with leading `./` when pattern has `./`', () => {
    const format = str => str.replace(/^\.\//, '');
    expect_truthy(!isMatch('./a/b/c/d/e/z/c.md', './a/**/j/**/z/*.md', { format }));
    expect_truthy(!isMatch('./a/b/c/j/e/z/c.txt', './a/**/j/**/z/*.md', { format }));
    expect_truthy(isMatch('./a/b/c/d/e/j/n/p/o/z/c.md', './a/**/j/**/z/*.md', { format }));
    expect_truthy(isMatch('./a/b/c/d/e/z/c.md', './a/**/z/*.md', { format }));
    expect_truthy(isMatch('./a/b/c/j/e/z/c.md', './a/**/j/**/z/*.md', { format }));
    expect_truthy(isMatch('./a/b/z/.a', './a/**/z/.a', { format }));
  });

  test('should match leading slashes', () => {
    expect_truthy(!isMatch('ef', '/*'));
    expect_truthy(isMatch('/ef', '/*'));
    expect_truthy(isMatch('/foo/bar.txt', '/foo/*'));
    expect_truthy(isMatch('/foo/bar.txt', '/foo/**'));
    expect_truthy(isMatch('/foo/bar.txt', '/foo/**/**/*.txt'));
    expect_truthy(isMatch('/foo/bar.txt', '/foo/**/**/bar.txt'));
    expect_truthy(isMatch('/foo/bar.txt', '/foo/**/*.txt'));
    expect_truthy(isMatch('/foo/bar.txt', '/foo/**/bar.txt'));
    expect_truthy(!isMatch('/foo/bar.txt', '/foo/*/bar.txt'));
    expect_truthy(!isMatch('/foo/bar/baz.txt', '/foo/*'));
    expect_truthy(isMatch('/foo/bar/baz.txt', '/foo/**'));
    expect_truthy(isMatch('/foo/bar/baz.txt', '/foo/**'));
    expect_truthy(isMatch('/foo/bar/baz.txt', '/foo/**/*.txt'));
    expect_truthy(isMatch('/foo/bar/baz.txt', '/foo/**/*/*.txt'));
    expect_truthy(isMatch('/foo/bar/baz.txt', '/foo/**/*/baz.txt'));
    expect_truthy(!isMatch('/foo/bar/baz.txt', '/foo/*.txt'));
    expect_truthy(isMatch('/foo/bar/baz.txt', '/foo/*/*.txt'));
    expect_truthy(!isMatch('/foo/bar/baz.txt', '/foo/*/*/baz.txt'));
    expect_truthy(!isMatch('/foo/bar/baz.txt', '/foo/bar**'));
    expect_truthy(isMatch('/foo/bar/baz/qux.txt', '**/*.txt'));
    expect_truthy(!isMatch('/foo/bar/baz/qux.txt', '**/.txt'));
    expect_truthy(!isMatch('/foo/bar/baz/qux.txt', '*/*.txt'));
    expect_truthy(!isMatch('/foo/bar/baz/qux.txt', '/foo/**.txt'));
    expect_truthy(isMatch('/foo/bar/baz/qux.txt', '/foo/**/*.txt'));
    expect_truthy(!isMatch('/foo/bar/baz/qux.txt', '/foo/*/*.txt'));
    expect_truthy(!isMatch('/foo/bar/baz/qux.txt', '/foo/bar**/*.txt'));
    expect_truthy(!isMatch('/.txt', '*.txt'));
    expect_truthy(!isMatch('/.txt', '/*.txt'));
    expect_truthy(!isMatch('/.txt', '*/*.txt'));
    expect_truthy(!isMatch('/.txt', '**/*.txt'));
    expect_truthy(!isMatch('/.txt', '*.txt', { dot: true }));
    expect_truthy(isMatch('/.txt', '/*.txt', { dot: true }));
    expect_truthy(isMatch('/.txt', '*/*.txt', { dot: true }));
    expect_truthy(isMatch('/.txt', '**/*.txt', { dot: true }));
  });

  test('should match double slashes', () => {
    expect_truthy(!isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/*'));
    expect_truthy(!isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/*'));
    expect_truthy(isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/**'));
    expect_truthy(!isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/**', { noglobstar: true }));
    expect_truthy(isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/**'));
    expect_truthy(isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/**/app.min.js'));
    expect_truthy(isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/*/*/app.min.js'));
    expect_truthy(isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/*/*/app.min.js', { noglobstar: true }));
    expect_truthy(!isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/*/app.min.js'));
    expect_truthy(!isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/*/app.min.js'));
    expect_truthy(isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/**/app.min.js'));
    expect_truthy(!isMatch('https://foo.com/bar/baz/app.min.js', 'https://foo.com/**/app.min.js', { noglobstar: true }));
  });
});
